INSERT INTO ITEM VALUES('Honeycrisp Apples - 3lb Bag - Good and Gather', 4.99, '($0.10/ounce)');
INSERT INTO ITEM VALUES('Organic Gala Apples - 2lb Bag - Good and Gather', 2.59, '($0.08/ounce)');
INSERT INTO ITEM VALUES('Fuji Apples - 3lb Bag - Good and Gather', 3.69, '($0.08/ounce)');
INSERT INTO ITEM VALUES('Pink Lady Apples - 3lb Bag - Good and Gather', 3.99, '($0.08/ounce)');
INSERT INTO ITEM VALUES("Once Upon a Farm Wild Rumpus Avocado, Pineapple Banana Organic Kids' Snack - 3.2oz Pouch", 2.99, '($0.93/ounce)');
INSERT INTO ITEM VALUES("Once Upon a Farm Strawberry Banana Swirl Organic Dairy-Free Kids' Smoothie - 4oz Pouch", 2.99, '($0.75/ounce)');
INSERT INTO ITEM VALUES('Organic Strawberry and Banana Frozen Fruit Blend - 32oz - Good and Gather', 10.79, '($0.34/ounce)');
INSERT INTO ITEM VALUES('Navel Oranges - 4lb Bag - Good and Gather', 4.99, '($0.08/ounce)');
INSERT INTO ITEM VALUES('Sun Beams Mandarin Oranges - 3lb - Good and Gather', 3.79, '($0.08/ounce)');
INSERT INTO ITEM VALUES('Traditional Medicinals Organic Throat Coat Lemon Echinacea Herbal Tea - 16ct', 5.39, '($4.77/ounce)');
INSERT INTO ITEM VALUES('Traditional Medicinals Organic EveryDay Detox Lemon Herbal Tea - 16ct', 5.39, '($6.34/ounce)');
INSERT INTO ITEM VALUES('Lemons - 2lb Bag - Good and Gather', 4.49, '($0.14/ounce)');
INSERT INTO ITEM VALUES('Poppi Cherry Lime Prebiotic Soda - 4pk/12 fl oz Cans', 9.49, '($0.20/fluid ounce)');
INSERT INTO ITEM VALUES('bubly Lime Sparkling Water - 8pk/12 fl oz Cans', 4.39, '($0.05/fluid ounce)');
INSERT INTO ITEM VALUES('Limes - 1lb Bag - Good and Gather', 3.19, '($0.20/ounce)');
INSERT INTO ITEM VALUES('GoGo SqueeZ Big Variety Pack Apple Mango Banana Passfruit Pineapple Peach - 42.3oz/10ct', 7.89, '($0.19/ounce)');
INSERT INTO ITEM VALUES('IZZE Pineapple Sparkling Juice - 6pk/8.4 fl oz Cans', 6.99, '($0.14/fluid ounce)');
INSERT INTO ITEM VALUES('Del Monte Pineapple Chunks in 100% Juice 20oz', 1.79, '($0.09/ounce)');
INSERT INTO ITEM VALUES('So Good So You Immunity Watermelon Strawberry Organic Probiotic Shot - 1.7 fl oz', 3.99, '($2.35/fluid ounce)');
INSERT INTO ITEM VALUES('MiO Strawberry Watermelon Liquid Water Enhancer - 3.24 fl oz Bottle', 5.49, '($1.69/fluid ounce)');
INSERT INTO ITEM VALUES('Watermelon Lime Sparkling Water - 8pk/12 fl oz Cans - Good and Gather', 3.29, '($0.03/fluid ounce)');
INSERT INTO ITEM VALUES('Organic Strawberries - 16oz', 4.69, '($0.29/ounce)');
INSERT INTO ITEM VALUES('Strawberries - 2lb', 8.69, '($0.27/ounce)');
INSERT INTO ITEM VALUES('Strawberries - 1lb', 3.29, '($0.21/ounce)');
INSERT INTO ITEM VALUES('Frozen Sliced Strawberries - 16oz - Good and Gather', 3.49, '($0.22/ounce)');
INSERT INTO ITEM VALUES('Jumbo Blueberries - 9.8oz', 5.99, '($0.61/ounce)');
INSERT INTO ITEM VALUES('Frozen Blueberries - 48oz - Good and Gather', 7.99, '($0.17/ounce)');
INSERT INTO ITEM VALUES('Frozen Blueberries - 12oz - Good and Gather', 2.99, '($0.25/ounce)');
INSERT INTO ITEM VALUES('Blueberries - 11.2oz', 3.99, '($0.36/ounce)');
INSERT INTO ITEM VALUES('Raspberries - 6oz', 3.69, '($0.62/ounce)');
INSERT INTO ITEM VALUES('Raspberries - 12oz', 6.99, '($0.58/ounce)');
INSERT INTO ITEM VALUES('Raspberries - 12oz', 6.99, '($0.58/ounce)');
INSERT INTO ITEM VALUES('Organic Raspberries - 6oz', 4.69, '($0.78/ounce)');
INSERT INTO ITEM VALUES('Blackberries - 6oz', 2.69, '($0.45/ounce)');
INSERT INTO ITEM VALUES('Blackberries - 12oz', 4.89, '($0.41/ounce)');
INSERT INTO ITEM VALUES('Blackberries - 12oz', 4.89, '($0.41/ounce)');
INSERT INTO ITEM VALUES('Organic Blackberries - 6oz', 4.69, '($0.78/ounce)');
INSERT INTO ITEM VALUES('Cotton Candy Grapes - 1.5lb', 7.49, '($0.31/ounce)');
INSERT INTO ITEM VALUES("Welch's 100% Grape Juice - 64 fl oz Bottle", 5.29, '($0.08/fluid ounce)');
INSERT INTO ITEM VALUES("Welch's Concord Grape Juice - 6pk/10 fl oz Bottles", 5.59, '($0.09/fluid ounce)');
INSERT INTO ITEM VALUES("Welch's 100% White Grape Juice - 64 fl oz Bottle", 5.29, '($0.08/fluid ounce)');
INSERT INTO ITEM VALUES('So Good So You Immunity Watermelon Strawberry Organic Probiotic Shot - 1.7 fl oz', 3.99, '($2.35/fluid ounce)');
INSERT INTO ITEM VALUES('MiO Strawberry Watermelon Liquid Water Enhancer - 3.24 fl oz Bottle', 5.49, '($1.69/fluid ounce)');
INSERT INTO ITEM VALUES('Watermelon Lime Sparkling Water - 8pk/12 fl oz Cans - Good and Gather', 3.29, '($0.03/fluid ounce)');
INSERT INTO ITEM VALUES('Simply Watermelon Juice Drink - 52 fl oz', 2.99, '($0.06/fluid ounce)');
INSERT INTO ITEM VALUES('Watermelon Spears - 1lb', 5.99, '($0.37/ounce)');
INSERT INTO ITEM VALUES('KeVita Peach Sparkling Prebiotic Lemonade - 12 fl oz', 2.49, '($0.21/fluid ounce)');
INSERT INTO ITEM VALUES('Sliced Peaches in 100% Juice 14.5oz - Market Pantry', 1.49, '($0.10/ounce)');
INSERT INTO ITEM VALUES('Waterloo Raspberry Nectarine Sparkling Water - 8pk/12 fl oz Cans', 4.29, '($0.04/fluid ounce)');
INSERT INTO ITEM VALUES('HappyBaby Clearly Crafted Bananas Plums and Granola Baby Food - 4oz', 2.19, '($0.55/ounce)');
INSERT INTO ITEM VALUES('Gerber 2nd Foods Wonderfoods, Banana, Plum and Grape Puree Tub - 8oz/2pk', 1.89, '($0.24/ounce)');
INSERT INTO ITEM VALUES('Plum Organics 8pk Mighty 4 Variety Flavor Baby Food Pouches - 32oz', 11.99, '($0.37/ounce)');
INSERT INTO ITEM VALUES('Capri Sun Strawberry Kiwi Pack - 10pk/6 fl oz Pouches', 2.79, '($0.05/fluid ounce)');
INSERT INTO ITEM VALUES('Naked Mighty Mango Juice Smoothie - 64 fl oz', 9.39, '($0.15/fluid ounce)');
INSERT INTO ITEM VALUES('Naked Mighty Mango Fruit Juice Smoothie - 15.2 fl oz', 3.69, '($0.24/fluid ounce)');
INSERT INTO ITEM VALUES('Frozen Mango Strawberry Fruit Blend - 48oz - Good and Gather', 10.79, '($0.22/ounce)');
INSERT INTO ITEM VALUES('HappyBaby Clearly Crafted Bananas Sweet Potatoes and Papayas Baby Meals - 4oz', 2.19, '($0.55/ounce)');
INSERT INTO ITEM VALUES('Hempz Sugarcane Sugarcane and Papaya Herbal Body Moisturizer Sugar and Passionfruit - 17 fl oz', 21.99, '($1.29/fluid ounce)');
INSERT INTO ITEM VALUES('HappyBaby Clearly Crafted Bananas Sweet Potatoes and Papayas Baby Meals - 4oz', 2.19, '($0.55/ounce)');
INSERT INTO ITEM VALUES('HappyTot Super Foods 4pk Organic Pears Mangos and Spinach with Super Chia - 16.88oz', 6.49, '($0.38/ounce)');
INSERT INTO ITEM VALUES('Kid-Sized Anjou Pears - 3lb Bag - Good and Gather', 4.39, '($0.09/ounce)');
INSERT INTO ITEM VALUES('Del Monte Diced Pears In 100% Juice Fruit Cups 4pk - 4oz', 2.99, '($0.19/ounce)');
INSERT INTO ITEM VALUES('Hass Avocados - 4ct - Good and Gather', 3.69, '($0.15/ounce)');
INSERT INTO ITEM VALUES('Organic Hass Avocados - 4ct - Good and Gather', 3.99, '($1.00/count)');
INSERT INTO ITEM VALUES('Frozen Diced Avocado - 10oz - Good and Gather', 3.49, '($0.35/ounce)');
INSERT INTO ITEM VALUES('Muir Glen Organic Diced Tomatoes No Salt Added - 14.5oz', 2.69, '($0.19/ounce)');
INSERT INTO ITEM VALUES('Muir Glen Fire Roasted Diced Tomatoes - 14oz', 2.69, '($0.19/ounce)');
INSERT INTO ITEM VALUES('Roma Tomatoes - 16oz - Good and Gather (Packaging May Vary)', 1.19, '($0.07/ounce)');
INSERT INTO ITEM VALUES('Premium Grape Tomatoes - 10oz - Good and Gather (Packaging May Vary)', 2.59, '($0.26/ounce)');
INSERT INTO ITEM VALUES('Shredded Green Leaf Lettuce - 4.5oz - Good and Gather', 2.19, '($0.49/ounce)');
INSERT INTO ITEM VALUES('Shredded Iceberg Lettuce - 8oz - Good and Gather', 2.19, '($0.27/ounce)');
INSERT INTO ITEM VALUES('Organic Spring Mix Lettuce - 5oz - Good and Gather', 3.29, '($0.66/ounce)');
INSERT INTO ITEM VALUES('Rana Spinach and Ricotta Ravioli - 10oz', 4.49, '($0.45/ounce)');
INSERT INTO ITEM VALUES('HappyBaby Clearly Crafted Green Beans Pears and Spinach Baby Food Pouch - 4oz', 2.19, '($0.55/ounce)');
INSERT INTO ITEM VALUES('Steam-in-Bag Spinach - 9oz - Good and Gather', 2.19, '($0.24/ounce)');
INSERT INTO ITEM VALUES('Organic Baby Spinach - 5oz - Good and Gather', 3.29, '($0.66/ounce)');
INSERT INTO ITEM VALUES('Broccoli Florets - 12oz - Good and Gather', 2.59, '($0.22/ounce)');
INSERT INTO ITEM VALUES('Frozen Broccoli Florets - 12oz - Good and Gather', 1.29, '($0.11/ounce)');
INSERT INTO ITEM VALUES('Organic Steam-in-Bag Broccoli Florets - 9oz - Good and Gather', 3.79, '($0.42/ounce)');
INSERT INTO ITEM VALUES('Organic Carrots - 1lb - Good and Gather', 1.29, '($0.08/ounce)');
INSERT INTO ITEM VALUES('Baby-Cut Carrots - 1lb - Good and Gather', 1.19, '($0.07/ounce)');
INSERT INTO ITEM VALUES('Organic Baby-Cut Carrots - 1lb - Good and Gather', 1.79, '($0.11/ounce)');
INSERT INTO ITEM VALUES('Carrot Sticks - 12oz - Good and Gather', 1.49, '($0.12/ounce)');
INSERT INTO ITEM VALUES('Alexia Frozen Waffle Cut Sweet Potato Seasoned Fries - 20oz', 5.49, '($0.27/ounce)');
INSERT INTO ITEM VALUES('Idahoan Gluten Free Original Mashed Potatoes - 13.75oz', 2.89, '($0.21/ounce)');
INSERT INTO ITEM VALUES('Russet Potatoes - 5lb - (Brand May Vary)', 3.59, '($0.04/ounce)');
INSERT INTO ITEM VALUES('Yellow Onions - 3lb Bag - Good and Gather', 2.79, '($0.06/ounce)');
INSERT INTO ITEM VALUES('Sweet Onions - 2lb Bag - Good and Gather', 1.99, '($0.06/ounce)');
INSERT INTO ITEM VALUES('Suja Organic Vegan Uber Greens - 46 fl oz', 11.19, '($0.24/fluid ounce)');
INSERT INTO ITEM VALUES('Suja Organic Elevated Nutrients Immunity Strawberry Guava - 12 fl oz', 4.99, '($0.42/fluid ounce)');
INSERT INTO ITEM VALUES('Celery Sticks - 20oz - Good and Gather (Packaging May Vary)', 3.19, '($0.16/ounce)');
INSERT INTO ITEM VALUES('Organic Celery Hearts - 16oz/2ct - Good and Gather', 3.49, '($0.22/ounce)');
INSERT INTO ITEM VALUES('Mini Cucumbers - 16oz Bag - Good and Gather (Packaging May Vary)', 1.99, '($0.12/ounce)');
INSERT INTO ITEM VALUES('Cucumber - 2ct', 1.79, '($0.08/ounce)');
INSERT INTO ITEM VALUES('Cucumber Mint Sparkling Water - 8pk/12 fl oz Cans - Good and Gather', 3.29, '($0.03/fluid ounce)');
INSERT INTO ITEM VALUES('Mezzetta Mild Roasted Red Bell Peppers - 16oz', 3.89, '($0.24/ounce)');
INSERT INTO ITEM VALUES('Mezzetta Mild Sliced Roasted Bell Pepper Strips - 16oz', 3.89, '($0.24/ounce)');
INSERT INTO ITEM VALUES('Tri-Colored Bell Peppers - 16oz/3ct - Good and Gather (Packaging May Vary)', 2.99, '($0.19/ounce)');
INSERT INTO ITEM VALUES('Green Bell Peppers - 2ct - Good and Gather', 1.89, '($0.94/count)');
INSERT INTO ITEM VALUES('Spice World Organic Minced Garlic - 4.5oz', 2.99, '($0.66/ounce)');
INSERT INTO ITEM VALUES('Spice World Minced Garlic - 8oz', 3.19, '($0.40/ounce)');
INSERT INTO ITEM VALUES('Spice World Minced Garlic - 8oz', 3.19, '($0.40/ounce)');
INSERT INTO ITEM VALUES('Gourmet Garden Gluten Free Ginger Stir-In Paste - 4oz', 4.19, '($1.05/ounce)');
INSERT INTO ITEM VALUES('Ground Ginger - 2oz - Good and Gather', 3.19, '($1.60/ounce)');
INSERT INTO ITEM VALUES('Gourmet Garden Gluten Free Ginger Stir-In Paste - 4oz', 4.19, '($1.05/ounce)');
INSERT INTO ITEM VALUES('Sliced White Mushrooms - 8oz - Good and Gather', 2.29, '($0.29/ounce)');
INSERT INTO ITEM VALUES('Sliced Baby Bella Mushrooms - 8oz - Good and Gather', 2.59, '($0.32/ounce)');
INSERT INTO ITEM VALUES('Baby Bella Mushrooms - 8oz - Good and Gather', 2.49, '($0.31/ounce)');
INSERT INTO ITEM VALUES('Whole White Mushrooms - 8oz - Good and Gather', 2.19, '($0.27/ounce)');
INSERT INTO ITEM VALUES('HappyBaby Clearly Crafted Pears Zucchini and Peas Baby Food - 4oz', 2.19, '($0.55/ounce)');
INSERT INTO ITEM VALUES('Beech-Nut Naturals Spinach, Zucchini and Peas Baby Food Jar - 4oz', 1.29, '($0.32/ounce)');
INSERT INTO ITEM VALUES('Organic Zucchini - 2ct', 3.19, '($1.60/count)');
INSERT INTO ITEM VALUES('Frozen Zucchini Spirals - 12oz - Good and Gather', 3.99, '($0.33/ounce)');
INSERT INTO ITEM VALUES("Kellogg's Corn Pops - 16.4oz", 5.29, '($0.32/ounce)');
INSERT INTO ITEM VALUES('Fritos Scoops! Corn Chips - 15.50oz', 6.69, '($0.43/ounce)');
INSERT INTO ITEM VALUES('Golden Sweet Whole Kernel Corn - 15.25oz - Good and Gather', 0.75, '($0.05/ounce)');
INSERT INTO ITEM VALUES('Del Monte Golden Sweet Whole Kernel Corn - 15.25oz', 1.69, '($0.11/ounce)');
INSERT INTO ITEM VALUES('Beech-Nut Naturals Green Beans Baby Food Jar - 4oz', 1.29, '($0.32/ounce)');
INSERT INTO ITEM VALUES('Green Beans - 12oz - Good and Gather', 2.59, '($0.22/ounce)');
INSERT INTO ITEM VALUES('Cut Green Beans 14.5oz - Good and Gather', 0.75, '($0.05/ounce)');
INSERT INTO ITEM VALUES('Organic Steam-in-Bag Green Beans - 12oz - Good and Gather', 3.99, '($0.33/ounce)');
INSERT INTO ITEM VALUES('Asparagus - 16oz', 3.69, '($0.23/ounce)');
INSERT INTO ITEM VALUES('Birds Eye Steamfresh Frozen Asparagus Spears - 8oz', 3.99, '($0.50/ounce)');
INSERT INTO ITEM VALUES('Frozen Riced Cauliflower Mushroom and Asparagus Medley - 10oz - Good and Gather', 2.79, '($0.28/ounce)');
INSERT INTO ITEM VALUES('Asparagus and Cheddar Stuffed Chicken Breasts - 18.03oz/4ct - Good and Gather', 11.49, '($0.64/ounce)');
INSERT INTO ITEM VALUES('Pepsi Cola Soda - 12pk/12 fl oz Cans', 7.79, '($0.05/fluid ounce)');
INSERT INTO ITEM VALUES('Zwita Shakshuka Eggplant and Sweet Potato - 10oz', 6.99, '($0.70/ounce)');
INSERT INTO ITEM VALUES('Reese Quartered Artichoke Hearts 14oz', 2.49, '($0.18/ounce)');
INSERT INTO ITEM VALUES('Signature Marinated Artichokes - 9.8oz - Good and Gather', 4.99, '($0.51/ounce)');
INSERT INTO ITEM VALUES('Spinach Artichoke Dip - 12oz - Good and Gather', 4.79, '($0.40/ounce)');
INSERT INTO ITEM VALUES('Good Foods Spinach Artichoke Parmesan Dairy Dip - 8oz', 4.49, '($0.56/ounce)');
INSERT INTO ITEM VALUES('Life Cuisine Protein Lovers Gluten Free Frozen Cauliflower Crust Three Meat Pizza - 6oz', 4.49, '($0.75/ounce)');
INSERT INTO ITEM VALUES('Cauliflower Florets - 12oz - Good and Gather', 2.59, '($0.22/ounce)');
INSERT INTO ITEM VALUES('Frozen Cauliflower - 12oz - Good and Gather', 1.69, '($0.14/ounce)');
INSERT INTO ITEM VALUES('Sweet Potatoes - 3lb Bag - Good and Gather', 2.49, '($0.05/ounce)');
INSERT INTO ITEM VALUES('Alexia Frozen Sweet Potato Fries - 20oz', 5.49, '($0.27/ounce)');
INSERT INTO ITEM VALUES('Alexia Frozen Waffle Cut Sweet Potato Seasoned Fries - 20oz', 5.49, '($0.27/ounce)');
INSERT INTO ITEM VALUES('Brussels Sprouts - 12oz - Good and Gather', , );
INSERT INTO ITEM VALUES('Shaved Brussels Sprouts - 9oz - Good and Gather', 2.69, '($0.30/ounce)');
INSERT INTO ITEM VALUES('Birds Eye Steamfresh Frozen Brussels Sprouts - 10.8oz', 2.19, '($0.20/ounce)');
INSERT INTO ITEM VALUES('La Choy Bean Sprouts 14oz', 1.79, '($0.13/ounce)');
INSERT INTO ITEM VALUES('HappyBaby Clearly Crafted Apples Guavas and Beets Baby Food - 4oz', 2.19, '($0.55/ounce)');
INSERT INTO ITEM VALUES("Aunt Nellie's Sliced Pickled Beets - 16oz", 1.99, '($0.12/ounce)');
INSERT INTO ITEM VALUES("Aunt Nellie's Whole Pickled Beets - 16oz", 1.99, '($0.12/ounce)');
INSERT INTO ITEM VALUES('Romaine Hearts - 3ct/22oz - Good and Gather', 2.89, '($0.13/ounce)');
INSERT INTO ITEM VALUES('Organic Romaine Hearts - 12oz/3ct - Good and Gather', 4.29, '($0.36/ounce)');
INSERT INTO ITEM VALUES('Hearts of Romaine - 9oz - Good and Gather', 3.19, '($0.35/ounce)');
INSERT INTO ITEM VALUES('Shredded Romaine Lettuce - 8oz - Good and Gather', 3.19, '($0.40/ounce)');
INSERT INTO ITEM VALUES('Organic Baby Arugula - 5oz - Good and Gather', 3.29, '($0.66/ounce)');
INSERT INTO ITEM VALUES('Signature Wood-Fired Prosciutto and Arugula Frozen Pizza - 15.52oz - Good and Gather', 7.49, '($0.48/ounce)');
INSERT INTO ITEM VALUES('Wood-Fired Spinach Feta Olive and Arugula Frozen Flatbread Pizza - 15.2oz - Good and Gather', 7.49, '($0.49/ounce)');
INSERT INTO ITEM VALUES('Signature Wood-Fired Tomato and Arugula Frozen Pizza - 15.34oz - Good and Gather', 7.49, '($0.49/ounce)');
INSERT INTO ITEM VALUES('HappyTot Fiber and Protein Organic Pears Kiwi and Kale Baby Food Pouch - 4oz', 1.59, '($0.40/ounce)');
INSERT INTO ITEM VALUES('HappyBaby Clearly Crafted Pears Kale and Spinach Baby Food Pouch - 4oz', 2.19, '($0.55/ounce)');
INSERT INTO ITEM VALUES('Chopped Kale - 16oz - Good and Gather', 3.69, '($0.23/ounce)');
INSERT INTO ITEM VALUES('Sweet Kale Chopped Salad Kit - 12oz - Good and Gather', 3.99, '($0.33/ounce)');
INSERT INTO ITEM VALUES('Glory Gluten Free Foods Seasoned Southern Style Collard Greens 27oz', 2.29, '($0.08/ounce)');
INSERT INTO ITEM VALUES('Fennel Seed - 1.75oz - Good and Gather', 1.99, '($1.14/ounce)');
INSERT INTO ITEM VALUES('Organic Fennel Seed - 1.6oz - Good and Gather', 3.49, '($2.18/ounce)');
INSERT INTO ITEM VALUES('Amber Glass Fennel and Pine Lidded Wooden Wick Jar Candle 9oz - Threshold', 13.00, '($1.44/ounce)');
INSERT INTO ITEM VALUES('Green Onions - 5.5oz - Good and Gather', 1.29, '($0.23/ounce)');
INSERT INTO ITEM VALUES('Yellow Onions - 3lb Bag - Good and Gather', 2.79, '($0.06/ounce)');
INSERT INTO ITEM VALUES('Sweet Onions - 2lb Bag - Good and Gather', 1.99, '($0.06/ounce)');
INSERT INTO ITEM VALUES('Green Beans - 12oz - Good and Gather', 2.59, '($0.22/ounce)');
INSERT INTO ITEM VALUES("Lawry's Garlic Salt - 11oz", 4.99, '($0.45/ounce)');
INSERT INTO ITEM VALUES("Lawry's Garlic Salt - 6oz", 3.99, '($0.67/ounce)');
INSERT INTO ITEM VALUES('Parsley Flakes - 0.25oz - Good and Gather', 1.19, '($4.76/ounce)');
INSERT INTO ITEM VALUES('Gourmet Garden Lightly Dried Parsley - 0.35oz', 4.19, '($11.97/ounce)');
INSERT INTO ITEM VALUES('Gourmet Garden Lightly Dried Cilantro - 0.35oz', 4.19, '($11.97/ounce)');
INSERT INTO ITEM VALUES("Bitchin' Cilantro Sauce - 8oz", 6.29, '($0.79/ounce)');
INSERT INTO ITEM VALUES('Cilantro Bunch - each', 1.19, '($0.30/ounce)');
INSERT INTO ITEM VALUES('Gourmet Garden Lightly Dried Cilantro - 0.35oz', 4.19, '($11.97/ounce)');
INSERT INTO ITEM VALUES('Gourmet Garden Lightly Dried Basil - 0.42oz', 4.19, '($9.98/ounce)');
INSERT INTO ITEM VALUES('Barilla Rustic Basil Pesto Sauce - 6.5oz', 3.99, '($0.61/ounce)');
INSERT INTO ITEM VALUES('Basil Leaves - 0.62oz - Good and Gather', 1.19, '($1.92/ounce)');
INSERT INTO ITEM VALUES('Gourmet Garden Lightly Dried Basil - 0.42oz', 4.19, '($9.98/ounce)');
INSERT INTO ITEM VALUES('McCormick Cracked Black Pepper, Garlic, Herb, Sea Salt Gluten Free All Purpose Seasoning - 4.37oz', 4.99, '($1.14/ounce)');
INSERT INTO ITEM VALUES('McCormick Italian Herb Seasoning Grinder - .77oz', 2.59, '($3.36/ounce)');
INSERT INTO ITEM VALUES('Thyme Leaves - .75oz - Good and Gather', 1.99, '($2.65/ounce)');
INSERT INTO ITEM VALUES('Ground Thyme - 1.75oz - Good and Gather', 3.19, '($1.82/ounce)');
INSERT INTO ITEM VALUES('Rosemary - .75oz - Good and Gather', 1.99, '($2.65/ounce)');
INSERT INTO ITEM VALUES('Organic Whole Rosemary - 1.2oz - Good and Gather', 3.49, '($2.91/ounce)');
INSERT INTO ITEM VALUES('Fairlife Lactose-Free Skim Milk - 52 fl oz', 4.69, '($0.09/fluid ounce)');
INSERT INTO ITEM VALUES('Fairlife Lactose-Free 2% Milk - 52 fl oz', 4.69, '($0.09/fluid ounce)');
INSERT INTO ITEM VALUES('Vitamin D Whole Milk - 1gal - Good and Gather', 4.19, '($0.03/fluid ounce)');
INSERT INTO ITEM VALUES('2% Reduced Fat Milk - 1gal - Good and Gather', 3.79, '($0.03/fluid ounce)');
INSERT INTO ITEM VALUES('Vital Farms Pasture-Raised Grade A Large Eggs - 12ct', 6.69, '($0.56/count)');
INSERT INTO ITEM VALUES('Vital Farms Pasture Raised Large Eggs - 18ct', 9.69, '($0.54/count)');
INSERT INTO ITEM VALUES('Cage-Free Large White Fresh Grade A Eggs (CA SEFS Compliant) - 36oz/18ct - Good and Gather (Packaging May Vary)', 3.69, '($0.20/count)');
INSERT INTO ITEM VALUES('Cage-Free Fresh Grade A Large Brown Eggs - 12ct - Good and Gather', 2.69, '($0.22/count)');
INSERT INTO ITEM VALUES('Country Crock Original Vegetable Oil Spread Tub - 15oz', 3.69, '($0.25/ounce)');
INSERT INTO ITEM VALUES('Kerrygold Grass-Fed Naturally Softer Pure Irish Butter - 8oz Tub', 4.49, '($0.56/ounce)');
INSERT INTO ITEM VALUES('Salted Butter - 1lb - Good and Gather', 4.39, '($0.27/ounce)');
INSERT INTO ITEM VALUES('Unsalted Butter - 1lb - Good and Gather', 4.39, '($0.27/ounce)');
INSERT INTO ITEM VALUES('Stonyfield Organic Fat Free Plain Greek Yogurt - 32oz', 7.29, '($0.23/ounce)');
INSERT INTO ITEM VALUES("Stonyfield Organic Kids' Strawberry and Mixed Berry Lowfat Yogurt - 16ct/2oz Tubes", 7.69, '($0.24/ounce)');
INSERT INTO ITEM VALUES('Greek Vanilla Nonfat Yogurt - 32oz - Good and Gather', 3.89, '($0.12/ounce)');
INSERT INTO ITEM VALUES('Greek Plain Nonfat Yogurt - 32oz - Good and Gather', 3.89, '($0.12/ounce)');
INSERT INTO ITEM VALUES('Kraft Singles American Cheese Slices - 16oz/24ct', 4.99, '($0.31/ounce)');
INSERT INTO ITEM VALUES('Kraft Singles American Cheese Slices - 12oz/16ct', 4.29, '($0.36/ounce)');
INSERT INTO ITEM VALUES('Shredded Mexican-Style Cheese - 8oz - Good and Gather', 2.29, '($0.29/ounce)');
INSERT INTO ITEM VALUES('Colby Jack Deli Sliced Cheese - 8oz/12 slices - Good and Gather', 2.29, '($0.29/ounce)');
INSERT INTO ITEM VALUES('Philadelphia Original Cream Cheese - 16oz/2ct', 5.99, '($0.37/ounce)');
INSERT INTO ITEM VALUES('Philadelphia Original Cream Cheese - 8oz', 3.39, '($0.42/ounce)');
INSERT INTO ITEM VALUES('Plain Cream Cheese Bar - 8oz - Good and Gather', 1.99, '($0.25/ounce)');
INSERT INTO ITEM VALUES('Philadelphia Original Cream Cheese - 16oz/2ct', 5.99, '($0.37/ounce)');
INSERT INTO ITEM VALUES('Ruffles Cheddar And Sour Cream Chips - 13oz', 6.69, '($0.54/ounce)');
INSERT INTO ITEM VALUES('Ruffles Oven Baked Cheddar and Sour Cream Flavored Potato Crisps - 6.25oz', 4.79, '($0.77/ounce)');
INSERT INTO ITEM VALUES('Sour Cream - 16oz - Good and Gather', 2.39, '($0.15/ounce)');
INSERT INTO ITEM VALUES('Sour Cream - 8oz - Good and Gather', 1.99, '($0.25/ounce)');
INSERT INTO ITEM VALUES("Ben and Jerry's Half Baked Chocolate and Vanilla Ice Cream - 16oz", 4.99, '($4.99/pint (usa))');
INSERT INTO ITEM VALUES('Half and Half - 32 fl oz (1qt) - Good and Gather', 2.99, '($0.09/fluid ounce)');
INSERT INTO ITEM VALUES('Half and Half - 16 fl oz (1pt) - Good and Gather', 1.89, '($0.12/fluid ounce)');
INSERT INTO ITEM VALUES('Half and Half - 0.5gal - Good and Gather', 5.99, '($0.09/fluid ounce)');
INSERT INTO ITEM VALUES('Heavy Whipping Cream - 16 fl oz (1pt) - Good and Gather', 2.99, '($0.19/fluid ounce)');
INSERT INTO ITEM VALUES('Heavy Whipping Cream - 32 fl oz (1qt) - Good and Gather', 4.99, '($0.16/fluid ounce)');
INSERT INTO ITEM VALUES('Organic Heavy Whipping Cream - 16 fl oz (1pt) - Good and Gather', 4.39, '($0.27/fluid ounce)');
INSERT INTO ITEM VALUES('Horizon Organic Heavy Whipping Cream - 16 fl oz (1pt)', 5.39, '($0.34/fluid ounce)');
INSERT INTO ITEM VALUES('1% Milkfat Small Curd Cottage Cheese - 24oz - Good and Gather', 2.79, '($0.12/ounce)');
INSERT INTO ITEM VALUES('4% Milkfat Small Curd Cottage Cheese - 24oz - Good and Gather', 2.79, '($0.12/ounce)');
INSERT INTO ITEM VALUES('Good Culture 2% Low-Fat Classic Cottage Cheese - 16oz', 3.89, '($0.24/ounce)');
INSERT INTO ITEM VALUES('1% Milkfat Small Curd Cottage Cheese - 16oz - Good and Gather', 1.99, '($0.12/ounce)');
INSERT INTO ITEM VALUES('Coffee mate French Vanilla Coffee Creamer - 32 fl oz (1qt)', 4.79, '($0.15/fluid ounce)');
INSERT INTO ITEM VALUES('Heavy Whipping Cream - 16 fl oz (1pt) - Good and Gather', 2.99, '($0.19/fluid ounce)');
INSERT INTO ITEM VALUES('Heavy Whipping Cream - 32 fl oz (1qt) - Good and Gather', 4.99, '($0.16/fluid ounce)');
INSERT INTO ITEM VALUES('Tillamook Farmstyle Mozzarella Shredded Cheese - 8oz', 4.19, '($0.52/ounce)');
INSERT INTO ITEM VALUES('Tillamook Farmstyle Italian Blend Shredded Cheese - 8oz', 4.19, '($0.52/ounce)');
INSERT INTO ITEM VALUES('Galbani Whole Milk Ricotta Cheese - 15oz', 4.29, '($0.29/ounce)');
INSERT INTO ITEM VALUES('Galbani Part Skim Milk Ricotta Cheese - 15oz', 4.29, '($0.29/ounce)');
INSERT INTO ITEM VALUES('Montchevre Crumbled Goat Cheese - 4oz', 3.59, '($0.90/ounce)');
INSERT INTO ITEM VALUES('Boursin Garlic And Herb Puck Cheese - 5.2oz', 5.59, '($1.08/ounce)');
INSERT INTO ITEM VALUES('Garlic and Herb Goat Cheese - 4oz - Good and Gather', 3.99, '($1.00/ounce)');
INSERT INTO ITEM VALUES('Goat Cheese Log - 8oz - Good and Gather', 4.99, '($0.62/ounce)');
INSERT INTO ITEM VALUES('Athenos Traditional Feta Cheese - 6oz', 4.19, '($0.70/ounce)');
INSERT INTO ITEM VALUES('Sargento Natural Baby Swiss Sliced Cheese - 7.5oz/11 slices', 3.69, '($0.53/ounce)');
INSERT INTO ITEM VALUES('Athenos Traditional Feta Cheese - 6oz', 4.19, '($0.70/ounce)');
INSERT INTO ITEM VALUES('Feta Cheese Crumbles - 6oz - Good and Gather', 3.99, '($0.67/ounce)');
INSERT INTO ITEM VALUES('Tillamook Farmstyle Mozzarella Shredded Cheese - 8oz', 4.19, '($0.52/ounce)');
INSERT INTO ITEM VALUES('Tillamook Farmstyle Whole Milk Mozzarella Cheese Slices - 8oz/9 slices', 4.39, '($0.55/ounce)');
INSERT INTO ITEM VALUES('Shredded Mozzarella Cheese - 8oz - Good and Gather', 2.29, '($0.29/ounce)');
INSERT INTO ITEM VALUES('Finely Shredded Mozzarella Cheese - 8oz - Good and Gather', 2.29, '($0.29/ounce)');
INSERT INTO ITEM VALUES('Tillamook Sharp Cheddar Cheese Block - 8oz', 4.49, '($0.56/ounce)');
INSERT INTO ITEM VALUES('Tillamook Farmstyle Sharp Cheddar Shredded Cheese - 8oz', 4.19, '($0.52/ounce)');
INSERT INTO ITEM VALUES('Shredded Sharp Cheddar Cheese - 8oz - Good and Gather', 2.29, '($0.29/ounce)');
INSERT INTO ITEM VALUES('Shredded Mild Cheddar Cheese - 8oz - Good and Gather', 2.29, '($0.29/ounce)');
INSERT INTO ITEM VALUES('Tillamook Sharp White Cheddar Cheese Snack Portions - 7.5oz/10ct', 4.39, '($0.59/ounce)');
INSERT INTO ITEM VALUES('Tillamook Farmstyle Italian Blend Shredded Cheese - 8oz', 4.19, '($0.52/ounce)');
INSERT INTO ITEM VALUES('Finely Shredded Parmesan Cheese - 6oz - Good and Gather', 2.29, '($0.38/ounce)');
INSERT INTO ITEM VALUES('Grated Parmesan Cheese - 8oz - Market Pantry', 2.99, '($0.37/ounce)');
INSERT INTO ITEM VALUES('Silk Unsweetened Vanilla Almond Milk - 0.5gal', 3.19, '($0.05/fluid ounce)');
INSERT INTO ITEM VALUES('Silk Unsweetened Almond Milk - 96 fl oz', 4.89, '($0.05/fluid ounce)');
INSERT INTO ITEM VALUES('Plant Based Unsweetened Original Almond Milk - 0.5gal - Good and Gather', 2.59, '($0.04/fluid ounce)');
INSERT INTO ITEM VALUES('Plant Based Unsweetened Vanilla Almond Milk - 0.5gal - Good and Gather', 2.59, '($0.04/fluid ounce)');
INSERT INTO ITEM VALUES('Silk Original Oat Milk - 0.5gal', 4.29, '($0.07/fluid ounce)');
INSERT INTO ITEM VALUES('Silk Extra Creamy Oat Milk - 0.5gal', 4.29, '($0.07/fluid ounce)');
INSERT INTO ITEM VALUES('Silk Organic Unsweetened Soy Milk - 0.5gal', 4.29, '($0.07/fluid ounce)');
INSERT INTO ITEM VALUES('Silk Original Soy Milk - 0.5gal', 4.29, '($0.07/fluid ounce)');
INSERT INTO ITEM VALUES('Califia Farms Toasted Coconut Almond Milk - 48 fl oz', 4.39, '($0.09/fluid ounce)');
INSERT INTO ITEM VALUES('Califia Farms Oat Barista Blend Oat Milk - 1qt', 4.59, '($0.14/fluid ounce)');
INSERT INTO ITEM VALUES('Organic Coconut Milk - 13.5oz - Good and Gather', 2.19, '($0.16/fluid ounce)');
INSERT INTO ITEM VALUES('Organic Unsweetened Coconut Milk - 32oz - Good and Gather', 1.99, '($0.06/fluid ounce)');
INSERT INTO ITEM VALUES('Oatly Oatmilk - 0.5gal', 5.39, '($0.08/fluid ounce)');
INSERT INTO ITEM VALUES('Oatly Barista Edition Oatmilk Ambient - 32oz', 5.59, '($0.17/fluid ounce)');
INSERT INTO ITEM VALUES('Original Oat Milk - 64 fl oz - Good and Gather', 3.79, '($0.06/fluid ounce)');
INSERT INTO ITEM VALUES('Oatly Oatmilk - 0.5gal', 5.39, '($0.08/fluid ounce)');
INSERT INTO ITEM VALUES('Ripple Dairy-Free Unsweetened Original Milk - 48 fl oz', 4.59, '($0.10/fluid ounce)');
INSERT INTO ITEM VALUES('Ripple Dairy-Free Chocolate Milk - 48 fl oz', 4.99, '($0.10/fluid ounce)');
INSERT INTO ITEM VALUES('Rice Dream Organic Enriched Original Rice Non-Dairy Beverage - 64 fl oz', 5.19, '($0.08/fluid ounce)');
INSERT INTO ITEM VALUES('Rice Dream Organic Enriched Vanilla Rice Drink Non-Dairy Beverage - 64 fl oz', 5.19, '($0.08/fluid ounce)');
INSERT INTO ITEM VALUES('Chobani Sweet Cream Coffee Creamer - 24 fl oz', 4.59, '($0.19/fluid ounce)');
INSERT INTO ITEM VALUES('Coffee mate Natural Bliss Sweet Cream Creamer - 32 fl oz (1qt)', 5.69, '($0.18/fluid ounce)');
INSERT INTO ITEM VALUES('Coffee mate French Vanilla Coffee Creamer - 32 fl oz (1qt)', 4.79, '($0.15/fluid ounce)');
INSERT INTO ITEM VALUES('Coffee mate French Vanilla Coffee Creamer - 64 fl oz (2qt)', 8.69, '($0.14/fluid ounce)');
INSERT INTO ITEM VALUES('Cool Whip Original Frozen Whipped Topping - 8oz', 2.29, '($0.29/ounce)');
INSERT INTO ITEM VALUES('Cool Whip Lite Frozen Whipped Topping - 8oz', 2.29, '($0.29/ounce)');
INSERT INTO ITEM VALUES('Original Whipped Dairy Topping - 13oz - Favorite Day', 3.59, '($0.28/ounce)');
INSERT INTO ITEM VALUES('Reddi-wip Original Whipped Dairy Cream Topping - 6.5oz', 3.39, '($0.52/ounce)');
INSERT INTO ITEM VALUES('All Natural 85/15 Ground Beef - 1lb - Good and Gather', 6.49, '($0.41/ounce)');
INSERT INTO ITEM VALUES('Organic 100% Grassfed 90/10 Ground Beef - 1lb - Good and Gather', 7.99, '($0.50/ounce)');
INSERT INTO ITEM VALUES("Laura's Lean Beef 96/4 Ground Beef - 1lb", 8.99, '($0.56/ounce)');
INSERT INTO ITEM VALUES('93/7 Ground Beef Patties - 1lb - Good and Gather', 7.49, '($0.47/ounce)');
INSERT INTO ITEM VALUES("Kevin's Cilantro Lime Chicken - 16oz", 9.99, '($0.62/ounce)');
INSERT INTO ITEM VALUES('Caulipower Frozen Dill Pickle Chicken Bites - 14oz', 8.99, '($0.64/ounce)');
INSERT INTO ITEM VALUES('Boneless and Skinless Chicken Breast - Frozen - 40oz - Good and Gather', 8.49, '($0.21/ounce)');
INSERT INTO ITEM VALUES('Oscar Mayer Bacon - 12oz', 6.99, '($0.58/ounce)');
INSERT INTO ITEM VALUES('Oscar Mayer Bacon - 16oz', 8.99, '($0.56/ounce)');
INSERT INTO ITEM VALUES('Oscar Mayer Bacon - 12oz', 6.99, '($0.58/ounce)');
INSERT INTO ITEM VALUES('Fully Cooked Bacon - 2.1oz - Market Pantry', 3.49, '($1.66/ounce)');
INSERT INTO ITEM VALUES('C. Wirthy and Co. Blackened Hand-Seasoned Atlantic Salmon Fillets - Frozen - 10oz', 10.99, '($1.10/ounce)');
INSERT INTO ITEM VALUES('C. Wirthy and Co. Teriyaki Hand-Seasoned Atlantic Salmon Fillets - Frozen - 10oz', 10.99, '($1.10/ounce)');
INSERT INTO ITEM VALUES('Atlantic Salmon - Frozen - 16oz - Good and Gather', 9.99, '($0.62/ounce)');
INSERT INTO ITEM VALUES('Alaska Keta Salmon Skinless Fillets - Frozen - 24oz - Good and Gather', 13.99, '($0.58/ounce)');
INSERT INTO ITEM VALUES('Sea Cuisine Garlic and Herb Tilapia - Frozen - 9oz', 9.99, '($1.11/ounce)');
INSERT INTO ITEM VALUES('Sea Cuisine Tortilla Tilapia - Frozen - 9oz', 9.99, '($1.11/ounce)');
INSERT INTO ITEM VALUES('Sea Cuisine Garlic and Herb Tilapia - Frozen - 9oz', 9.99, '($1.11/ounce)');
INSERT INTO ITEM VALUES('Farm Raised Swai Fillets - Frozen - 24oz - Good and Gather', 6.99, '($0.29/ounce)');
INSERT INTO ITEM VALUES("Gorton's Crunchy Breaded Fish Sticks Club Pack - Frozen - 51oz", 13.19, '($0.26/ounce)');
INSERT INTO ITEM VALUES("Gorton's Beer Battered Fish Fillets - Frozen - 18.2oz", 7.39, '($0.41/ounce)');
INSERT INTO ITEM VALUES('Large Tail Off Peeled and Deveined Raw Shrimp - Frozen - 41-50ct per lb/16oz - Good and Gather', 6.99, '($0.44/ounce)');
INSERT INTO ITEM VALUES('Small Tail Off Peeled and Deveined Cooked Shrimp - Frozen - 71-90ct/16oz - Good and Gather', 7.49, '($0.47/ounce)');
INSERT INTO ITEM VALUES('Jennie-O All-Natural 93/7 Ground Turkey - 16oz', 4.49, '($0.28/ounce)');
INSERT INTO ITEM VALUES('Jennie-O 90/10 Ground Turkey Roll - 1lb', 3.99, '($0.25/ounce)');
INSERT INTO ITEM VALUES('Jennie-O All-Natural 99/1 Ground Turkey Breast - 16oz', 5.99, '($0.37/ounce)');
INSERT INTO ITEM VALUES('Jennie-O 93/7 Lean Ground Turkey Family Pack - 48oz', 11.89, '($0.25/ounce)');
INSERT INTO ITEM VALUES('Hillshire Farms Ultra Thin Oven Roasted Turkey Breast - 9oz', 4.79, '($0.53/ounce)');
INSERT INTO ITEM VALUES('Applegate Natural Uncured Turkey Pepperoni - 4oz', 5.89, '($1.47/ounce)');
INSERT INTO ITEM VALUES('Smoked Honey Turkey Breast Ultra-Thin Deli Slices - 9oz - Good and Gather', 3.99, '($0.44/ounce)');
INSERT INTO ITEM VALUES('Lower Sodium Oven Roasted Turkey Breast Ultra-Thin Deli Slices - 8oz - Good and Gather', 3.99, '($0.50/ounce)');
INSERT INTO ITEM VALUES('StarKist Chunk Light Tuna in Water Pouch - 2.6oz', 1.49, '($0.57/ounce)');
INSERT INTO ITEM VALUES('StarKist Tuna Creations Deli Style Tuna Salad Pouch - 3oz', 1.49, '($0.50/ounce)');
INSERT INTO ITEM VALUES('StarKist Chunk Light Tuna in Water - 5oz/4ct', 4.79, '($0.24/ounce)');
INSERT INTO ITEM VALUES('Chunk Light Tuna in Water - 5oz/4pk - Good and Gather', 3.79, '($0.19/ounce)');
INSERT INTO ITEM VALUES('StarKist Chunk Light Tuna in Water Pouch - 2.6oz', 1.49, '($0.57/ounce)');
INSERT INTO ITEM VALUES('StarKist Tuna Creations Lemon Pepper Pouch - 2.6oz', 1.49, '($0.57/ounce)');
INSERT INTO ITEM VALUES('Bumble Bee Premium Wild Pink Salmon 14.75oz', 4.39, '($0.30/ounce)');
INSERT INTO ITEM VALUES('Wild Planet Wild Alaskan Pink Salmon - 6oz', 4.39, '($0.73/ounce)');
INSERT INTO ITEM VALUES("Gorton's Crunchy Breaded Fish Sticks Club Pack - Frozen - 51oz", 13.19, '($0.26/ounce)');
INSERT INTO ITEM VALUES("Gorton's Beer Battered Fish Fillets - Frozen - 18.2oz", 7.39, '($0.41/ounce)');
INSERT INTO ITEM VALUES('Large Tail Off Peeled and Deveined Raw Shrimp - Frozen - 41-50ct per lb/16oz - Good and Gather', 6.99, '($0.44/ounce)');
INSERT INTO ITEM VALUES('Jumbo Tail On Peeled and Deveined Raw Shrimp - Frozen - 26-30ct per lb/16oz - Good and Gather', 7.99, '($0.50/ounce)');
INSERT INTO ITEM VALUES('Country Archer All Natural Grass Fed Original Beef Jerky - 2.5oz', 7.49, '($3.00/ounce)');
INSERT INTO ITEM VALUES('Country Archer Zero Sugar Classic Beef Jerky - 2oz', 7.49, '($3.75/ounce)');
INSERT INTO ITEM VALUES("Jack Link's Original Beef Jerky Family Size - 8oz", 9.99, '($1.25/ounce)');
INSERT INTO ITEM VALUES("Jack Link's Protein On-the-Go Original Beef Jerky - 3.125oz", 7.99, '($2.56/ounce)');
INSERT INTO ITEM VALUES('Hillshire Farms Ultra Thin Deli Select Honey Ham - 9oz', 4.79, '($0.53/ounce)');
INSERT INTO ITEM VALUES('Hillshire Farm Black Forest Ham - 9oz', 4.79, '($0.53/ounce)');
INSERT INTO ITEM VALUES('Uncured Honey Ham Ultra-Thin Deli Slices - 9oz - Good and Gather', 3.99, '($0.44/ounce)');
INSERT INTO ITEM VALUES('Uncured Black Forest Ham Ultra-Thin Deli Slices - 9oz - Good and Gather', 3.99, '($0.44/ounce)');
INSERT INTO ITEM VALUES('Oscar Mayer Natural Slow Roasted Turkey Breast Sliced Lunch Meat - 8oz', 5.49, '($0.69/ounce)');
INSERT INTO ITEM VALUES('Hillshire Farms Ultra Thin Oven Roasted Turkey Breast - 9oz', 4.79, '($0.53/ounce)');
INSERT INTO ITEM VALUES('Smoked Honey Turkey Breast Ultra-Thin Deli Slices - 9oz - Good and Gather', 3.99, '($0.44/ounce)');
INSERT INTO ITEM VALUES('Lower Sodium Oven Roasted Turkey Breast Ultra-Thin Deli Slices - 16oz - Good and Gather', 6.99, '($0.44/ounce)');
INSERT INTO ITEM VALUES('Oscar Mayer Bologna Sliced Lunch Meat - 16oz', 2.99, '($0.19/ounce)');
INSERT INTO ITEM VALUES('Oscar Mayer Deli Fresh Rotisserie Seasoned Chicken Breast Sliced Lunch Meat Family Size - 16oz', 6.99, '($0.44/ounce)');
INSERT INTO ITEM VALUES('Oscar Mayer Deli Fresh Oven Roasted Turkey Breast Sliced Lunch Meat - 9oz', 4.99, '($0.55/ounce)');
INSERT INTO ITEM VALUES('Smoked Honey Turkey Breast Ultra-Thin Deli Slices - 9oz - Good and Gather', 3.99, '($0.44/ounce)');
INSERT INTO ITEM VALUES('Ball Park Beef Franks - 15oz/8ct', 4.49, '($0.30/ounce)');
INSERT INTO ITEM VALUES('Ball Park Bun Size Angus Beef Franks - 14oz/8ct', 5.39, '($0.39/ounce)');
INSERT INTO ITEM VALUES('Oscar Mayer Original Uncured Wieners Hot Dogs - 16oz/10ct', 3.19, '($0.20/ounce)');
INSERT INTO ITEM VALUES('Ball Park Bun Size Beef Franks - 15oz/8ct', 4.49, '($0.30/ounce)');
INSERT INTO ITEM VALUES('Aidells Chicken and Apple Smoked Chicken Sausage - 12oz/4ct', 5.99, '($0.50/ounce)');
INSERT INTO ITEM VALUES('Jones Dairy Farm Frozen All Natural Turkey Sausage Links - 10ct/5oz', 3.49, '($0.70/ounce)');
INSERT INTO ITEM VALUES('Johnsonville Beddar with Cheddar Smoked Sausage - 14oz', 4.29, '($0.31/ounce)');
INSERT INTO ITEM VALUES('Andouille Chicken Sausage - 12oz - Good and Gather', 3.99, '($0.33/ounce)');
INSERT INTO ITEM VALUES("Gorton's Breaded Minced Fish Sticks - Frozen - 24.5oz/44ct", 7.39, '($0.30/ounce)');
INSERT INTO ITEM VALUES("Gorton's Crunchy Breaded Fish Sticks Club Pack - Frozen - 51oz", 13.19, '($0.26/ounce)');
INSERT INTO ITEM VALUES("Gorton's Breaded Minced Fish Sticks - Frozen - 24.5oz/44ct", 7.39, '($0.30/ounce)');
INSERT INTO ITEM VALUES("Gorton's Crunchy Breaded Fish Sticks Club Pack - Frozen - 51oz", 13.19, '($0.26/ounce)');
INSERT INTO ITEM VALUES('Kidfresh Frozen Chicken Nuggets - 16.35oz', 9.99, '($0.61/ounce)');
INSERT INTO ITEM VALUES('Applegate Naturals Family Size Chicken Nuggets - Frozen - 16oz', 13.39, '($0.84/ounce)');
INSERT INTO ITEM VALUES('Dinosaur Shaped Frozen Chicken Nuggets - 29oz - Good and Gather', 5.49, '($0.19/ounce)');
INSERT INTO ITEM VALUES('Kidfresh Frozen Chicken Nuggets - 16.35oz', 9.99, '($0.61/ounce)');
INSERT INTO ITEM VALUES('Bubba Burger Angus Beef Chuck Patties - Frozen - 2lbs/6ct', 14.89, '($0.47/ounce)');
INSERT INTO ITEM VALUES('Bubba Burger Beef Patties - Frozen - 32oz', 14.89, '($0.47/ounce)');
INSERT INTO ITEM VALUES('Steakhouse Seasoned Beef Patties - Frozen - 3LBs - Good and Gather', 13.49, '($0.28/ounce)');
INSERT INTO ITEM VALUES('DiGiorno Four Cheese Frozen Pizza with Rising Crust - 28.2oz', 6.49, '($0.23/ounce)');
INSERT INTO ITEM VALUES('California Pizza Kitchen Thin Crust Frozen White Pizza - 12.6oz', 8.59, '($0.68/ounce)');
INSERT INTO ITEM VALUES('Red Baron Frozen Pizza Classic Crust Pepperoni - 20.6oz', 4.99, '($0.24/ounce)');
INSERT INTO ITEM VALUES('Red Baron Frozen Pizza Classic Crust 4-Cheese - 21.06oz', 4.99, '($0.24/ounce)');
INSERT INTO ITEM VALUES('Feel Good Foods Gluten Free Frozen Mozzarella Sticks - 8oz', 6.89, '($0.86/ounce)');
INSERT INTO ITEM VALUES('Frozen Mixed Vegetables - 12oz - Good and Gather', 0.99, '($0.08/ounce)');
INSERT INTO ITEM VALUES('Birds Eye Steamfresh Frozen Mixed Vegetables - 10oz', 1.49, '($0.15/ounce)');
INSERT INTO ITEM VALUES('Birds Eye Steamfresh Frozen Vegetables - 10.8oz', 2.99, '($0.28/ounce)');
INSERT INTO ITEM VALUES('Sambazon Açaí Original Blend Superfruit Frozen Smoothie Packs - 400g', 5.59, '($0.40/ounce)');
INSERT INTO ITEM VALUES('Tru Fru White and Milk Chocolate Frozen Whole Raspberries - 8oz', 6.69, '($0.84/ounce)');
INSERT INTO ITEM VALUES('Strawberry Banana Frozen Fruit Blend - 48oz - Good and Gather', 9.99, '($0.21/ounce)');
INSERT INTO ITEM VALUES('Triple Berry Frozen Fruit Blend - 48oz - Good and Gather', 12.69, '($0.26/ounce)');
INSERT INTO ITEM VALUES("Nature's Own Honey Wheat Bread - 20oz", 3.79, '($0.19/ounce)');
INSERT INTO ITEM VALUES("Nature's Own Butter Bread - 20oz", 3.79, '($0.19/ounce)');
INSERT INTO ITEM VALUES('Alfaros Artesano Bread - 20oz', 3.99, '($0.20/ounce)');
INSERT INTO ITEM VALUES('White Sandwich Bread - 20oz - Market Pantry', 1.39, '($0.07/ounce)');
INSERT INTO ITEM VALUES("Dave's Killer Bread Plain Awesome Organic Bagels - 16.75oz", 6.49, '($0.39/ounce)');
INSERT INTO ITEM VALUES("Dave's Killer Bread Epic Everything Organic Bagels - 16.75oz", 6.49, '($0.39/ounce)');
INSERT INTO ITEM VALUES("Thomas' Plain Bagels - 20oz/6ct", 4.39, '($0.22/ounce)');
INSERT INTO ITEM VALUES("Thomas' Everything Bagels - 20oz/6ct", 4.39, '($0.22/ounce)');
INSERT INTO ITEM VALUES("Dave's Killer Bread Organic Classic English Muffins - 13.2oz/6ct", 5.39, '($0.41/ounce)');
INSERT INTO ITEM VALUES("Dave's Killer Bread Organic Rockin' Grains English Muffins - 13.2oz/6ct", 5.39, '($0.41/ounce)');
INSERT INTO ITEM VALUES("Thomas' Regular English Muffins - 13oz/6ct", 3.59, '($0.28/ounce)');
INSERT INTO ITEM VALUES("Thomas' Light Multigrain English Muffins - 12oz/6ct", 3.59, '($0.30/ounce)');
INSERT INTO ITEM VALUES("Nature's Own Perfectly Crafted Brioche Hamburger Bun - 18oz", 4.29, '($0.24/ounce)');
INSERT INTO ITEM VALUES("King's Hawaiian Sweet Hamburger Buns - 12.8oz/8ct", 4.99, '($0.39/ounce)');
INSERT INTO ITEM VALUES('Hamburger Buns - 12oz/8ct - Market Pantry', 1.59, '($0.13/ounce)');
INSERT INTO ITEM VALUES('Ball Park Hamburger Buns - 15oz/8ct', 2.99, '($0.20/ounce)');
INSERT INTO ITEM VALUES('Oscar Mayer Bun-Length Uncured Wieners Hot Dogs - 16oz/8ct', 3.19, '($0.20/ounce)');
INSERT INTO ITEM VALUES('Oscar Mayer Original Classic Beef Uncured Franks Hot Dogs - 15oz/10ct', 4.39, '($0.29/ounce)');
INSERT INTO ITEM VALUES('Hot Dog Buns - 11oz/8ct - Market Pantry', 1.59, '($0.14/ounce)');
INSERT INTO ITEM VALUES('Enriched White Hot Dog Buns - 12oz/8ct - Market Pantry', 1.59, '($0.13/ounce)');
INSERT INTO ITEM VALUES('Wheat Dinner Rolls - 14oz/12ct - Favorite Day', 3.99, '($0.29/ounce)');
INSERT INTO ITEM VALUES("King's Hawaiian Original Hawaiian Sweet Rolls - 12oz/12ct", 4.79, '($0.40/ounce)');
INSERT INTO ITEM VALUES("King's Hawaiian Savory Butter Sweet Rolls - 12oz/12ct", 4.79, '($0.40/ounce)');
INSERT INTO ITEM VALUES("King's Hawaiian Sweet Rolls - 24ct /24oz", 8.49, '($0.35/ounce)');
INSERT INTO ITEM VALUES('Old El Paso Tortilla Pockets - 8.4oz', 3.39, '($0.40/ounce)');
INSERT INTO ITEM VALUES("Old El Paso Stand 'n Stuff Flour Tortillas - 6.7oz/8ct", 3.79, '($0.57/ounce)');
INSERT INTO ITEM VALUES('Mission Taco Size Flour Tortillas - 17.5oz/10ct', 3.19, '($0.18/ounce)');
INSERT INTO ITEM VALUES('Mission Fajita Flour Tortillas - 23oz/20ct', 3.69, '($0.16/ounce)');
INSERT INTO ITEM VALUES('Stonefire Dippers Original Naan - 7.05oz', 4.29, '($0.61/ounce)');
INSERT INTO ITEM VALUES('Stonefire Mini Original Naan - 7.05oz/4ct', 3.19, '($0.45/ounce)');
INSERT INTO ITEM VALUES('Stonefire Original Naan Bread - 8.8oz/2ct', 3.19, '($0.36/ounce)');
INSERT INTO ITEM VALUES('Stonefire Garlic Mini Naan - 4ct', 3.19, '($0.45/ounce)');
INSERT INTO ITEM VALUES('Jimmy Dean Delights Turkey Sausage, Egg Whites, and Cheese Frozen Croissant - 4ct', 8.89, '($0.46/ounce)');
INSERT INTO ITEM VALUES('Hot Pockets Applewood Bacon Egg and Cheese Croissant Frozen Crust Sandwiches - 2ct/8.5oz', 3.79, '($0.45/ounce)');
INSERT INTO ITEM VALUES('Hostess Donettes Powdered Mini Donuts - 10oz', 2.59, '($0.26/ounce)');
INSERT INTO ITEM VALUES('Hostess Donettes Frosted Mini Donuts - 10.75oz', 2.59, '($0.24/ounce)');
INSERT INTO ITEM VALUES('Cheese Danish - 14oz - Favorite Day', 4.49, '($0.32/ounce)');
INSERT INTO ITEM VALUES('Blueberry White Chocolate Chunk Mini Scones - 10.25oz - Favorite Day', 4.99, '($0.49/ounce)');
INSERT INTO ITEM VALUES('Hostess Donettes Powdered Mini Donuts - 10oz', 2.59, '($0.26/ounce)');
INSERT INTO ITEM VALUES('Hostess Donettes Frosted Mini Donuts - 10.75oz', 2.59, '($0.24/ounce)');
INSERT INTO ITEM VALUES('Hostess Donettes Powdered Mini Donuts - 10oz', 2.59, '($0.26/ounce)');
INSERT INTO ITEM VALUES('Hostess Donettes Frosted Mini Donuts - 10.75oz', 2.59, '($0.24/ounce)');
INSERT INTO ITEM VALUES('Garden Lites Gluten Free Veggies Made Great Frozen Banana Chocolate Chip Muffins - 12oz/6ct', 6.49, '($0.54/ounce)');
INSERT INTO ITEM VALUES('Garden Lites Gluten Free Veggies Made Great Frozen Blueberry Oat Muffins - 12oz/6ct', 6.49, '($0.54/ounce)');
INSERT INTO ITEM VALUES('Blueberry Streusel Muffins - 4ct/14oz - Favorite Day', 4.29, '($0.31/ounce)');
INSERT INTO ITEM VALUES('Blueberry Streusel and Cinnamon Coffee Cake Muffins Variety Pack - 14oz/4ct - Favorite Day', 4.29, '($0.31/ounce)');
INSERT INTO ITEM VALUES("Tate's Bake Shop Chocolate Chip Cookies - 7oz", 6.39, '($0.91/ounce)');
INSERT INTO ITEM VALUES('Keebler Vienna Fingers Cookies Original - 12oz', 3.79, '($0.32/ounce)');
INSERT INTO ITEM VALUES('Little Debbie Cosmic Brownies - 6ct/13.1oz', 2.79, '($0.21/ounce)');
INSERT INTO ITEM VALUES('Betty Crocker Fudge Brownie Mix - 16.3oz', 2.29, '($0.14/ounce)');
INSERT INTO ITEM VALUES('Little Debbie Cosmic Brownies - 6ct/13.1oz', 2.79, '($0.21/ounce)');
INSERT INTO ITEM VALUES('Betty Crocker Fudge Brownie Mix - 16.3oz', 2.29, '($0.14/ounce)');
INSERT INTO ITEM VALUES('Hostess Chocolate Cup Cakes - 8ct/12.7oz', 3.69, '($0.29/ounce)');
INSERT INTO ITEM VALUES('Hostess Ding Dongs - 10ct/12.7oz', 3.69, '($0.29/ounce)');
INSERT INTO ITEM VALUES('Chocolate and Vanilla Mini Cupcakes - 10oz/12ct - Favorite Day', 4.79, '($0.48/ounce)');
INSERT INTO ITEM VALUES('Hostess Chocolate Cup Cakes - 8ct/12.7oz', 3.69, '($0.29/ounce)');
INSERT INTO ITEM VALUES('Betty Crocker Yellow Cake Mix - 13.25oz', 1.79, '($0.14/ounce)');
INSERT INTO ITEM VALUES('Betty Crocker Chocolate Fudge Super Moist Cake Mix - 13.25oz', 1.79, '($0.14/ounce)');
INSERT INTO ITEM VALUES('Little Debbie Strawberry Shortcake Rolls - 6ct/13oz', 2.79, '($0.21/ounce)');
INSERT INTO ITEM VALUES('Sara Lee Frozen Family Size All Butter Pound Cake - 16oz', 5.99, '($0.37/ounce)');
INSERT INTO ITEM VALUES("Ben and Jerry's Topped Ice Cream Dirt Cake Frozen Dessert - 15.2oz", 4.99, '($0.33/ounce)');
INSERT INTO ITEM VALUES('Edwards Frozen Chocolate Creme Pie - 25.5oz', 7.59, '($0.30/ounce)');
INSERT INTO ITEM VALUES("Marie Callender's Frozen Dutch Apple Pie - 38oz", 7.99, '($0.21/ounce)');
INSERT INTO ITEM VALUES("Annie's Organic Cinnamon Rolls with Icing - 17.5oz/5ct", 7.49, '($0.43/ounce)');
INSERT INTO ITEM VALUES('Little Debbie Honey Buns Breakfast Pastries - 6ct/10.6oz', 2.79, '($0.26/ounce)');
INSERT INTO ITEM VALUES('Pillsbury Cinnamon Rolls with Icing - 12.4oz/8ct', 3.49, '($0.28/ounce)');
INSERT INTO ITEM VALUES('Pillsbury Grands! Cinnamon Rolls with Icing - 17.5oz/5ct', 5.49, '($0.31/ounce)');
INSERT INTO ITEM VALUES('Blueberry White Chocolate Chunk Mini Scones - 10.25oz - Favorite Day', 4.99, '($0.49/ounce)');
INSERT INTO ITEM VALUES('Mini Orange Cranberry Scones - 10.25oz - Favorite Day', 4.99, '($0.49/ounce)');
INSERT INTO ITEM VALUES('Jimmy Dean Biscuit Sausage Snack Size Frozen Sandwiches - 17oz', 6.49, '($0.38/ounce)');
INSERT INTO ITEM VALUES('belVita Blueberry Breakfast Biscuits - 12ct', 8.99, '($0.43/ounce)');
INSERT INTO ITEM VALUES('Pillsbury Grands! Southern Homestyle Buttermilk Biscuits - 16.3oz/8ct', 3.49, '($0.21/ounce)');
INSERT INTO ITEM VALUES('Pillsbury Grands! Flaky Layers Biscuits - 16.3oz/8ct', 3.49, '($0.21/ounce)');
INSERT INTO ITEM VALUES('Premium Saltine Crackers, Original - 16oz', 3.99, '($0.25/ounce)');
INSERT INTO ITEM VALUES('Simple Mills Sea Salt - 4.25oz', 5.39, '($1.27/ounce)');
INSERT INTO ITEM VALUES('Entertainment Collection Cracker Variety - 13.1oz - Good and Gather', 4.99, '($0.38/ounce)');
INSERT INTO ITEM VALUES('Sea Salt Pita Crackers - 5oz - Good and Gather', 2.99, '($0.60/ounce)');
INSERT INTO ITEM VALUES('Frito Lay Classic Mix - 42ct', 21.99, '($0.56/ounce)');
INSERT INTO ITEM VALUES('Frito Lay Flavor Mix 42ct', 21.99, '($0.53/ounce)');
INSERT INTO ITEM VALUES('Frito-Lay Variety Pack Classic Mix - 18ct', 11.99, '($0.67/ounce)');
INSERT INTO ITEM VALUES('Ruffles Original Flavor Party Size Ridged Potato Chips - 13oz', 6.69, '($0.51/ounce)');
INSERT INTO ITEM VALUES('Nature Valley Sweet N Salty Granola Bars - 18ct/1.49oz', 8.99, '($0.25/ounce)');
INSERT INTO ITEM VALUES('CLIF Bar Chocolate Chip Energy Bar Minis - 20ct', 17.59, '($0.89/ounce)');
INSERT INTO ITEM VALUES('Nature Valley Sweet and Salty Dark Chocolate-Peanut and Almond Granola Bars - 7.4oz/6ct', 3.59, '($0.50/ounce)');
INSERT INTO ITEM VALUES("Nature Valley Crunchy Oats 'N Honey Granola Bars - 12ct", 3.59, '($0.40/ounce)');
INSERT INTO ITEM VALUES("Kellogg's Frosted Bran - 17.7oz", 5.29, '($0.30/ounce)');
INSERT INTO ITEM VALUES("Kellogg's Special K Iced Vanilla Latte - 18.2oz", 5.29, '($0.29/ounce)');
INSERT INTO ITEM VALUES('Quaker Lower Sugar Variety Pack Oatmeal - 9.3oz', 3.69, '($0.40/ounce)');
INSERT INTO ITEM VALUES('Quaker Oats Old Fashioned Oats - 42oz', 4.99, '($0.12/ounce)');
INSERT INTO ITEM VALUES('Quaker Instant Oatmeal Maple Brown Sugar 8ct', 3.69, '($0.30/ounce)');
INSERT INTO ITEM VALUES('Quaker Fruit and Cream Instant Oatmeal Variety - 8ct/9.8oz', 3.69, '($0.44/ounce)');
INSERT INTO ITEM VALUES('Pearl Milling Company Buttermilk Complete Pancake and Waffle Mix - 2lb', 3.49, '($0.11/ounce)');
INSERT INTO ITEM VALUES('Pearl Milling Company Original Pancake and Waffle Mix - 2lb', 3.49, '($0.11/ounce)');
INSERT INTO ITEM VALUES('Pearl Milling Company Buttermilk Complete Pancake and Waffle Mix - 2lb', 3.49, '($0.11/ounce)');
INSERT INTO ITEM VALUES('Krusteaz Buttermilk Pancake Mix - 2lb', 3.19, '($0.10/ounce)');
INSERT INTO ITEM VALUES('Pearl Milling Company Buttermilk Complete Pancake and Waffle Mix - 2lb', 3.49, '($0.11/ounce)');
INSERT INTO ITEM VALUES('Pearl Milling Company Original Complete Pancake and Waffle Mix - 2lb', 3.49, '($0.11/ounce)');
INSERT INTO ITEM VALUES('Krusteaz Belgian Waffle Mix - 28oz', 3.19, '($0.11/ounce)');
INSERT INTO ITEM VALUES('Buttermilk Pancake and Waffle Mix - 32oz - Good and Gather', 2.89, '($0.09/ounce)');
INSERT INTO ITEM VALUES("Bob's Red Mill Gluten Free 1-to-1 Baking Flour - 44oz", 9.79, '($0.22/ounce)');
INSERT INTO ITEM VALUES("Bob's Red Mill Gluten Free Super Fine Almond Flour - 16oz", 9.49, '($0.59/ounce)');
INSERT INTO ITEM VALUES('Unbleached All Purpose Flour - 5lbs - Good and Gather', 2.89, '($0.04/ounce)');
INSERT INTO ITEM VALUES('All Purpose Flour - 5lbs - Market Pantry', 2.89, '($0.04/ounce)');
INSERT INTO ITEM VALUES('Truvia Original Calorie-Free Sweetener from the Stevia Leaf - 40 packets/2.82oz', 3.79, '($1.34/ounce)');
INSERT INTO ITEM VALUES('Truvia Original Calorie-Free Sweetener from the Stevia Leaf Spoonable - 9.8oz', 6.99, '($0.71/ounce)');
INSERT INTO ITEM VALUES('Granulated Sugar - 4lbs - Good and Gather', 3.39, '($0.05/ounce)');
INSERT INTO ITEM VALUES('Domino Premium Pure Cane Granulated Sugar 4 lb', 3.49, '($0.05/ounce)');
INSERT INTO ITEM VALUES('Clabber Girl Gluten Free Double Acting Baking Powder - 8.1oz', 2.79, '($0.34/ounce)');
INSERT INTO ITEM VALUES('Double Acting Baking Powder - 8.1oz - Good and Gather', 2.19, '($0.27/ounce)');
INSERT INTO ITEM VALUES('ARM and HAMMER Pure Baking Soda - 1lb', 1.69, '($0.11/ounce)');
INSERT INTO ITEM VALUES('ARM and HAMMER Pure Baking Soda - 1lb', 1.69, '($0.11/ounce)');
INSERT INTO ITEM VALUES('Baking Soda - 16oz - Good and Gather', 0.99, '($0.06/ounce)');
INSERT INTO ITEM VALUES('McCormick Pure Vanilla Extract - 2oz', 7.39, '($3.70/fluid ounce)');
INSERT INTO ITEM VALUES('Pure Vanilla Extract - 2oz - Good and Gather', 6.29, '($3.15/ounce)');
INSERT INTO ITEM VALUES('McCormick Pure Vanilla Extract - 1oz', 3.99, '($3.99/fluid ounce)');
INSERT INTO ITEM VALUES('McCormick Pure Vanilla Extract - 2oz', 7.39, '($3.70/fluid ounce)');
INSERT INTO ITEM VALUES('Nestle Toll House Semi-Sweet Chocolate Chips - 12oz', 3.39, '($0.28/ounce)');
INSERT INTO ITEM VALUES("Lily's Milk Style Chocolate Chips - 9oz", 7.79, '($0.87/ounce)');
INSERT INTO ITEM VALUES('Semi Sweet Chocolate Morsels - 12oz - Good and Gather', 2.59, '($0.22/ounce)');
INSERT INTO ITEM VALUES('Nestle Toll House Semi-Sweet Chocolate Chips - 12oz', 3.39, '($0.28/ounce)');
INSERT INTO ITEM VALUES('Navitas Organics Unsweetened Cacao Nibs - 4oz', 6.99, '($1.75/ounce)');
INSERT INTO ITEM VALUES('Natural Unsweetened Cocoa Powder - 8oz - Good and Gather', 2.79, '($0.35/ounce)');
INSERT INTO ITEM VALUES("Hershey's Natural Unsweetened Cocoa - 8oz", 5.59, '($0.70/ounce)');
INSERT INTO ITEM VALUES('Ghirardelli Unsweetened Cocoa - 8oz', 5.49, '($0.69/ounce)');
INSERT INTO ITEM VALUES("Nature Nate's 100% Pure Raw Unfiltered Organic Honey – 16oz", 9.99, '($0.62/ounce)');
INSERT INTO ITEM VALUES('Local Hive Colorado Raw and Unfiltered Honey -12oz', 6.49, '($0.54/ounce)');
INSERT INTO ITEM VALUES('Pure Clover Honey - 12oz - Good and Gather', 4.19, '($0.35/ounce)');
INSERT INTO ITEM VALUES('Organic Raw Unfiltered Pure Honey - 12oz - Good and Gather', 4.99, '($0.42/ounce)');
INSERT INTO ITEM VALUES('Pearl Milling Company Original Syrup - 24 fl oz.', 3.69, '($0.15/fluid ounce)');
INSERT INTO ITEM VALUES('Pearl Milling Company Butter Rich Syrup - 24 fl oz.', 3.69, '($0.15/fluid ounce)');
INSERT INTO ITEM VALUES('100% Pure Maple Syrup - 12 fl oz - Good and Gather', 7.99, '($0.67/fluid ounce)');
INSERT INTO ITEM VALUES('100% Pure Maple Syrup - 32 fl oz - Good and Gather', 17.79, '($0.56/fluid ounce)');
INSERT INTO ITEM VALUES('Pearl Milling Company Original Syrup - 24 fl oz.', 3.69, '($0.15/fluid ounce)');
INSERT INTO ITEM VALUES('Pearl Milling Company Butter Rich Syrup - 24 fl oz.', 3.69, '($0.15/fluid ounce)');
INSERT INTO ITEM VALUES('Original Pancake Syrup - 24oz - Favorite Day', 2.29, '($0.10/ounce)');
INSERT INTO ITEM VALUES('Pearl Milling Company Original Syrup - 24 fl oz.', 3.69, '($0.15/fluid ounce)');
INSERT INTO ITEM VALUES("Smucker's Seedless Strawberry Jam - 18oz", 4.19, '($0.23/ounce)');
INSERT INTO ITEM VALUES("Smucker's Natural Red Raspberry Fruit Spread - 17.25oz", 4.59, '($0.27/ounce)');
INSERT INTO ITEM VALUES("Smucker's Seedless Strawberry Jam - 18oz", 4.19, '($0.23/ounce)');
INSERT INTO ITEM VALUES("Smucker's Seedless Blackberry Jam - 18oz", 4.49, '($0.25/ounce)');
INSERT INTO ITEM VALUES('Jif To Go Creamy Peanut Butter - 12oz/8pk', 3.19, '($0.27/ounce)');
INSERT INTO ITEM VALUES('Jif No Added Sugar* Peanut Butter - 15.5oz', 3.39, '($0.22/ounce)');
INSERT INTO ITEM VALUES('Creamy Peanut Butter - 16oz - Good and Gather', 1.69, '($0.11/ounce)');
INSERT INTO ITEM VALUES('Jif Creamy Peanut Butter - 16oz', 3.19, '($0.20/ounce)');
INSERT INTO ITEM VALUES("Justin's Classic Almond Butter - 12oz", 7.49, '($0.62/ounce)');
INSERT INTO ITEM VALUES("Justin's Vanilla Almond Butter - 12oz", 7.49, '($0.62/ounce)');
INSERT INTO ITEM VALUES('No Stir Creamy Almond Butter 16oz - Good and Gather', 7.39, '($0.46/ounce)');
INSERT INTO ITEM VALUES('Stir Creamy Almond Butter 16oz - Good and Gather', 7.39, '($0.46/ounce)');
INSERT INTO ITEM VALUES('Nutella Chocolate Hazelnut Spread - 13oz', 4.19, '($0.32/ounce)');
INSERT INTO ITEM VALUES('Nutella Ferrero Chocolate Hazelnut Spread - 26.5oz', 7.99, '($0.30/ounce)');
INSERT INTO ITEM VALUES('Nutella Ferrero Chocolate Hazelnut Spread - 26.5oz', 7.99, '($0.30/ounce)');
INSERT INTO ITEM VALUES('Nutella Hazelnut Spread - 35.2oz', 10.19, '($0.29/ounce)');
INSERT INTO ITEM VALUES('Honey Maid Honey Graham Crackers - 14.4oz', 4.89, '($0.34/ounce)');
INSERT INTO ITEM VALUES('Honey Maid Fresh Stacks Honey Graham Crackers - 12.2oz/6ct', 4.89, '($0.40/ounce)');
INSERT INTO ITEM VALUES('Honey Maid Honey Graham Crackers - 14.4oz', 4.89, '($0.34/ounce)');
INSERT INTO ITEM VALUES('Honey Maid Fresh Stacks Honey Graham Crackers - 12.2oz/6ct', 4.89, '($0.40/ounce)');
INSERT INTO ITEM VALUES('Betty Crocker Vanilla Super Moist Cake Mix - 13.25oz', 1.79, '($0.14/ounce)');
INSERT INTO ITEM VALUES('Betty Crocker Delights Rainbow Chip Super Moist Cake Mix - 13.25oz', 1.99, '($0.15/ounce)');
INSERT INTO ITEM VALUES('Betty Crocker Vanilla Super Moist Cake Mix - 13.25oz', 1.79, '($0.14/ounce)');
INSERT INTO ITEM VALUES('Betty Crocker Delights Rainbow Chip Super Moist Cake Mix - 13.25oz', 1.99, '($0.15/ounce)');
INSERT INTO ITEM VALUES('Betty Crocker Fudge Brownie Mix - 16.3oz', 2.29, '($0.14/ounce)');
INSERT INTO ITEM VALUES('Betty Crocker Supreme Chocolate Chunk Brownie Mix - 18oz', 2.89, '($0.16/ounce)');
INSERT INTO ITEM VALUES('Duncan Hines Chewy Fudge Brownie Mix - 18.3oz', 1.79, '($0.10/ounce)');
INSERT INTO ITEM VALUES('Betty Crocker Fudge Brownie Mix - 16.3oz', 2.29, '($0.14/ounce)');
INSERT INTO ITEM VALUES('Betty Crocker Chocolate Chip Cookie Mix - 17.5oz', 2.89, '($0.17/ounce)');
INSERT INTO ITEM VALUES('Betty Crocker Chocolate Chip Cookie Mix - 7.5oz', 1.79, '($0.24/ounce)');
INSERT INTO ITEM VALUES('Betty Crocker Chocolate Chip Cookie Mix - 17.5oz', 2.89, '($0.17/ounce)');
INSERT INTO ITEM VALUES('Betty Crocker Oatmeal Chocolate Chip Cookie Mix - 17.5oz', 2.89, '($0.17/ounce)');
INSERT INTO ITEM VALUES('Pillsbury Ready-to-Bake Pie Crusts - 14.1oz/2ct', 4.99, '($0.35/ounce)');
INSERT INTO ITEM VALUES('Pillsbury Deep Dish Frozen Pie Crusts - 9in/2ct', 3.29, '($0.27/ounce)');
INSERT INTO ITEM VALUES('Graham Cracker Pie Crust - 6oz - Favorite Day', 1.59, '($0.27/ounce)');
INSERT INTO ITEM VALUES('Keebler Ready Crust Graham Pie Crust - 4oz/6ct', 3.39, '($0.85/ounce)');
INSERT INTO ITEM VALUES('Reddi-wip Original Whipped Dairy Cream Topping - 6.5oz', 3.39, '($0.52/ounce)');
INSERT INTO ITEM VALUES('Reddi-wip Original Whipped Cream - 13oz', 4.79, '($0.37/ounce)');
INSERT INTO ITEM VALUES('Original Whipped Dairy Topping - 13oz - Favorite Day', 3.59, '($0.28/ounce)');
INSERT INTO ITEM VALUES('Extra Creamy Whipped Dairy Topping - 13oz - Favorite Day', 3.59, '($0.28/ounce)');
INSERT INTO ITEM VALUES('Arrowhead 100% Natural Spring Water - 32pk/16.9 fl oz Bottles', 7.39, '($0.01/fluid ounce)');
INSERT INTO ITEM VALUES('Arrowhead Brand 100% Mountain Spring Water - 2.5 gal Jug', 6.89, '($0.02/fluid ounce)');
INSERT INTO ITEM VALUES('Purified Drinking Water - 24pk/16.9 fl oz Bottles - Good and Gather', 3.49, '($0.01/fluid ounce)');
INSERT INTO ITEM VALUES('Purified Water - 32pk/16.9 fl oz Bottles - Good and Gather', 4.69, '($0.01/fluid ounce)');
INSERT INTO ITEM VALUES('Coca-Cola - 12pk/12 fl oz Cans', 7.99, '($0.06/fluid ounce)');
INSERT INTO ITEM VALUES('Pepsi Cola Soda - 12pk/12 fl oz Cans', 7.79, '($0.05/fluid ounce)');
INSERT INTO ITEM VALUES('Dr Pepper Soda - 12pk/12 fl oz Cans', 7.79, '($0.05/fluid ounce)');
INSERT INTO ITEM VALUES('Canada Dry Ginger Ale Soda - 12pk/12 fl oz Cans', 6.99, '($0.05/fluid ounce)');
INSERT INTO ITEM VALUES('Tropicana Zero Sugar Summer Splash Punch Drink - 52 fl oz', 3.19, '($0.06/fluid ounce)');
INSERT INTO ITEM VALUES('V8 Splash Berry Blend Juice - 64 fl oz Bottle', 2.79, '($0.04/fluid ounce)');
INSERT INTO ITEM VALUES('Minute Maid Fruit Punch Juice - 59 fl oz', 1.99, '($0.03/fluid ounce)');
INSERT INTO ITEM VALUES('100% Apple Juice - 64 fl oz Bottle - Market Pantry', 1.99, '($0.03/fluid ounce)');
INSERT INTO ITEM VALUES('Lipton Black Tea Bags - 100ct', 4.89, '($0.61/ounce)');
INSERT INTO ITEM VALUES('Tazo Glazed Lemon Loaf Dessert Delights Tea Bags - 15ct', 3.49, '($3.17/ounce)');
INSERT INTO ITEM VALUES('Pukka Selection Box - 45ct', 21.99, '($1.31/ounce)');
INSERT INTO ITEM VALUES('Tiesta Tea Top Seller Sampler, Loose Leaf Tea - 8ct', 22.99, '($2.02/ounce)');
INSERT INTO ITEM VALUES('POWERADE Mountain Berry Blast Sports Drink - 8pk/20 fl oz Bottles', 6.49, '($0.04/fluid ounce)');
INSERT INTO ITEM VALUES('Gatorade Zero Mixed Flavor Variety Pack Sports Drink - 18pk/12 fl oz Bottles', 11.69, '($0.05/fluid ounce)');
INSERT INTO ITEM VALUES('Gatorade Fruit Punch Sports Drink - 20 fl oz Bottle', 2.49, '($0.12/fluid ounce)');
INSERT INTO ITEM VALUES('BODYARMOR Strawberry Banana Sports Drink - 8pk/12 fl oz Bottles', 6.49, '($0.07/fluid ounce)');
INSERT INTO ITEM VALUES('Monster Energy Zero Ultra - 12pk/16 fl oz Cans', 21.49, '($0.11/fluid ounce)');
INSERT INTO ITEM VALUES('5 Hour Energy Shot Regular Strength - Berry - 1.93 fl oz/10pk', 19.39, '($1.00/fluid ounce)');
INSERT INTO ITEM VALUES('Alani Cosmic Stardust Energy Drink - 12 fl oz Can', 2.69, '($0.22/fluid ounce)');
INSERT INTO ITEM VALUES('Alani Juicy Peach Energy Drink - 12 fl oz Can', 2.69, '($0.22/fluid ounce)');
INSERT INTO ITEM VALUES('Ripple Kids Unsweetened Original Milk Alternative - 48 fl oz', 4.99, '($0.10/fluid ounce)');
INSERT INTO ITEM VALUES('Ripple Dairy-Free Unsweetened Original Milk - 48 fl oz', 4.59, '($0.10/fluid ounce)');
INSERT INTO ITEM VALUES('Plant Based Unsweetened Vanilla Almond Milk - 0.5gal - Good and Gather', 2.59, '($0.04/fluid ounce)');
INSERT INTO ITEM VALUES('Organic Unsweetened Coconut Milk - 32oz - Good and Gather', 1.99, '($0.06/fluid ounce)');
INSERT INTO ITEM VALUES('Health-Ade Organic Vegan Pink Lady Apple Kombucha - 16 fl oz', 3.49, '($0.22/fluid ounce)');
INSERT INTO ITEM VALUES('Health-Ade Passion Fruit Tangerine Kombucha - 16 fl oz', 3.49, '($0.22/fluid ounce)');
INSERT INTO ITEM VALUES("GT's Synergy Trilogy Organic Kombucha - 48 fl oz", 8.89, '($0.19/fluid ounce)');
INSERT INTO ITEM VALUES('Health-Ade Organic Vegan Pink Lady Apple Kombucha - 16 fl oz', 3.49, '($0.22/fluid ounce)');
INSERT INTO ITEM VALUES('Tropicana Zero Sugar Lively Lemonade Drink - 52 fl oz', 3.19, '($0.06/fluid ounce)');
INSERT INTO ITEM VALUES('Tropicana Zero Sugar Passionfruit Lemonade Drink - 52 fl oz', 3.19, '($0.06/fluid ounce)');
INSERT INTO ITEM VALUES('Simply Lemonade - 52 fl oz', 2.99, '($0.06/fluid ounce)');
INSERT INTO ITEM VALUES('Simply Lemonade - 89 fl oz', 4.89, '($0.05/fluid ounce)');
INSERT INTO ITEM VALUES('Liquid Death Armless Palmer Tea - 8pk/19.2 fl oz Cans', 16.49, '($0.11/fluid ounce)');
INSERT INTO ITEM VALUES('Lipton Lemon Sweetened Iced Tea Mix - 50.3oz', 8.59, '($0.17/ounce)');
INSERT INTO ITEM VALUES('Pure Leaf Unsweetened Iced Tea - 64 fl oz Bottle', 3.59, '($0.06/fluid ounce)');
INSERT INTO ITEM VALUES('AriZona Arnold Palmer Lite Half Iced Tea and Half Lemonade - 128 fl oz Jug', 3.49, '($0.03/fluid ounce)');
INSERT INTO ITEM VALUES('Crystal Light On The Go Natural Pink Lemonade Drink Mix - 10pk/0.13oz Pouches', 3.19, '($2.45/ounce)');
INSERT INTO ITEM VALUES('Crystal Light Energy On The Go Wild Strawberry Drink Mix - 10pk/0.11oz Pouches', 3.19, '($2.90/ounce)');
INSERT INTO ITEM VALUES('Crystal Light Energy On The Go Wild Strawberry Drink Mix - 10pk/0.11oz Pouches', 3.19, '($2.90/ounce)');
INSERT INTO ITEM VALUES('Crystal Light Liquid Strawberry Lemonade Drink Mix - 1.62 fl oz Bottle', 3.39, '($2.09/fluid ounce)');
INSERT INTO ITEM VALUES('Siete Grain Free Cinnamon Chips Churro Strips – 5oz', 5.39, '($1.08/ounce)');
INSERT INTO ITEM VALUES('Kettle Brand Sea Salt and Vinegar Kettle Potato Chips - 7.5oz', 3.69, '($0.49/ounce)');
INSERT INTO ITEM VALUES('Frito-Lay Variety Pack Classic Mix - 18ct', 11.99, '($0.67/ounce)');
INSERT INTO ITEM VALUES('Ruffles Original Flavor Party Size Ridged Potato Chips - 13oz', 6.69, '($0.51/ounce)');
INSERT INTO ITEM VALUES('SkinnyPop Original Popcorn Skinny Pack - 6ct - 3.9oz', 5.99, '($1.54/ounce)');
INSERT INTO ITEM VALUES('SkinnyPop Original Popcorn Family Size - 8oz', 5.89, '($0.74/ounce)');
INSERT INTO ITEM VALUES('Pop Secret Microwave Popcorn Movie Theater Butter Flavor - 3oz/12ct', 6.39, '($0.17/ounce)');
INSERT INTO ITEM VALUES("Orville Redenbacher's Movie Theater Butter Microwave Popcorn - 12ct", 6.89, '($0.17/ounce)');
INSERT INTO ITEM VALUES('Rold Gold Tiny Twists Pretzels - 16oz', 3.99, '($0.25/ounce)');
INSERT INTO ITEM VALUES('Rold Gold Sticks Pretzels - 16oz', 3.99, '($0.25/ounce)');
INSERT INTO ITEM VALUES('Rold Gold Tiny Twists Pretzels - 16oz', 3.99, '($0.25/ounce)');
INSERT INTO ITEM VALUES('Mini Pretzel Twists - 25oz - Market Pantry', 4.49, '($0.18/ounce)');
INSERT INTO ITEM VALUES('Premium Saltine Crackers, Original - 16oz', 3.99, '($0.25/ounce)');
INSERT INTO ITEM VALUES("Kellogg's Club Snack Stacks Crackers - Original 12.5oz", 4.29, '($0.34/ounce)');
INSERT INTO ITEM VALUES('Entertainment Collection Cracker Variety - 13.1oz - Good and Gather', 4.99, '($0.38/ounce)');
INSERT INTO ITEM VALUES('Ritz Original Crackers - Fresh Stacks - 11.8oz', 3.99, '($0.34/ounce)');
INSERT INTO ITEM VALUES('KIND Thins Dark Chocolate Nuts Sea Salt - 7.4oz/10ct', 7.99, '($1.08/ounce)');
INSERT INTO ITEM VALUES('KIND Thins Peanut Butter Dark Chocolate and Dark Chocolate Cherry Cashew Bars Variety Pack – 20ct', 14.99, '($1.01/ounce)');
INSERT INTO ITEM VALUES('Sea Salt Dry Roasted Pistachio Kernels - 5.5oz - Good and Gather', 4.99, '($0.91/ounce)');
INSERT INTO ITEM VALUES('Mixed Nuts with Peanuts - 15oz - Good and Gather', 5.49, '($0.37/ounce)');
INSERT INTO ITEM VALUES('Chex Mix Cheddar Snack Mix - 15oz', 3.99, '($0.27/ounce)');
INSERT INTO ITEM VALUES('Chex Mix Traditional Snack Mix Bags - 17.5oz/10ct', 6.89, '($0.39/ounce)');
INSERT INTO ITEM VALUES('Monster Trail Mix - 36oz - Favorite Day', 8.79, '($0.24/ounce)');
INSERT INTO ITEM VALUES('Monster Trail Mix - 14oz - Favorite Day', 4.49, '($0.32/ounce)');
INSERT INTO ITEM VALUES('Country Archer All Natural Grass Fed Original Beef Jerky - 2.5oz', 7.49, '($3.00/ounce)');
INSERT INTO ITEM VALUES('Country Archer Zero Sugar Classic Beef Jerky - 2oz', 7.49, '($3.75/ounce)');
INSERT INTO ITEM VALUES("Jack Link's Original Beef Jerky Family Size - 8oz", 9.99, '($1.25/ounce)');
INSERT INTO ITEM VALUES("Jack Link's Protein On-the-Go Original Beef Jerky - 3.125oz", 7.99, '($2.56/ounce)');
INSERT INTO ITEM VALUES("Nature Valley Protein Oats 'n Honey Crunchy Granola - 11oz", 4.99, '($0.45/ounce)');
INSERT INTO ITEM VALUES('Nature Valley Protein Granola Oats and Honey Family Size Cereal - 17oz', 7.29, '($0.43/ounce)');
INSERT INTO ITEM VALUES('Honey Almond Granola - 12oz - Good and Gather', 5.39, '($0.45/ounce)');
INSERT INTO ITEM VALUES('French Vanilla Almond Granola - 12oz - Good and Gather', 4.89, '($0.41/ounce)');
INSERT INTO ITEM VALUES('Sun-Maid Mediterranean Dried Apricots Bag - 6oz', 4.29, '($0.72/ounce)');
INSERT INTO ITEM VALUES('Ocean Spray Reduced Sugar Craisins - 5oz', 2.49, '($0.50/ounce)');
INSERT INTO ITEM VALUES('Freeze Dried Strawberry Slices Multipack - 6ct/2.1oz - Good and Gather', 7.29, '($3.47/ounce)');
INSERT INTO ITEM VALUES('Apple, Strawberry, and Peach Freeze Dried Fruit Blend - 1oz - Good and Gather', 4.59, '($4.59/ounce)');
INSERT INTO ITEM VALUES('Froot Loops Cereal Breakfast Bar - 18ct/12.6oz', 6.99, '($0.55/ounce)');
INSERT INTO ITEM VALUES('Rice Krispies Treats Homestyle Original - 6.98oz/6ct', 4.99, '($0.71/ounce)');
INSERT INTO ITEM VALUES('Strawberry Cereal Bars - 8ct - Market Pantry', 2.59, '($0.25/ounce)');
INSERT INTO ITEM VALUES('Blueberry Cereal Bars 8ct - Market Pantry', 2.59, '($0.25/ounce)');
INSERT INTO ITEM VALUES("WELCH'S Fruit Snacks Mixed Fruit - 17.6oz/22ct", 5.99, '($0.34/ounce)');
INSERT INTO ITEM VALUES("WELCH'S Fruit Snacks Berries N' Cherries and Fruit Punch - 17.6oz/22ct", 5.99, '($0.34/ounce)');
INSERT INTO ITEM VALUES("WELCH'S Fruit Snacks Mixed Fruit - 17.6oz/22ct", 5.99, '($0.34/ounce)');
INSERT INTO ITEM VALUES("Welch's Fruit Snacks Mixed Fruit - 32oz/40ct", 8.99, '($0.28/ounce)');
INSERT INTO ITEM VALUES('Quaker Lightly Salted Gluten Free Rice Cakes - 4.47oz', 3.79, '($0.85/ounce)');
INSERT INTO ITEM VALUES('Quaker Chocolate Crunch Large Rice - Cakes 7.23oz', 3.79, '($0.52/ounce)');
INSERT INTO ITEM VALUES('Quaker Lightly Salted Gluten Free Rice Cakes - 4.47oz', 3.79, '($0.85/ounce)');
INSERT INTO ITEM VALUES('Quaker Caramel Corn Gluten Free Rice Cakes - 6.5oz', 3.79, '($0.58/ounce)');
INSERT INTO ITEM VALUES('Jell-O Chocolate Vanilla Swirls Sugar Free Pudding Cups Snack - 14.5oz/4ct', 3.39, '($0.23/ounce)');
INSERT INTO ITEM VALUES('Jell-O Original Chocolate Vanilla Swirls Pudding Cups Snack - 15.5oz/4ct', 3.39, '($0.22/ounce)');
INSERT INTO ITEM VALUES('Jell-O Chocolate Vanilla Swirls Sugar Free Pudding Cups Snack - 14.5oz/4ct', 3.39, '($0.23/ounce)');
INSERT INTO ITEM VALUES('Snack Pack Chocolate Fudge and Milk Chocolate Swirl Pudding - 39oz/12ct', 3.49, '($0.09/ounce)');
INSERT INTO ITEM VALUES('GoGo squeeZ Fruit and VeggieZ, Variety Peach/Strawberry - 3.2oz/12ct', 7.99, '($0.21/ounce)');
INSERT INTO ITEM VALUES('GoGo squeeZ Fruit and VeggieZ Blueberry/Pear - 12ct/38.4oz', 7.99, '($0.21/ounce)');
INSERT INTO ITEM VALUES('Unsweetened Applesauce Cups - 6ct - Good and Gather', 2.19, '($0.09/ounce)');
INSERT INTO ITEM VALUES('Cinnamon Applesauce Cups - 6ct - Good and Gather', 2.19, '($0.09/ounce)');
INSERT INTO ITEM VALUES('Chobani Mixed Berry on the Bottom Low-Fat Vanilla Greek Yogurt - 4ct/5.3oz Cups', 4.39, '($0.21/ounce)');
INSERT INTO ITEM VALUES('Chobani Flip Low-Fat Chocolate Peanut Butter Cup Greek Yogurt- 4.5oz', 1.49, '($0.33/ounce)');
INSERT INTO ITEM VALUES('Oikos Triple Zero Vanilla Greek Yogurt - 32oz Tub', 5.49, '($0.17/ounce)');
INSERT INTO ITEM VALUES('Oikos Triple Zero Mixed Berry Greek Yogurt - 4ct/5.3oz Cups', 4.69, '($0.22/ounce)');
INSERT INTO ITEM VALUES('Keebler Club and Cheddar Sandwich Crackers - 8ct', 3.99, '($0.36/ounce)');
INSERT INTO ITEM VALUES('Ritz Bits Cheese Cracker Sandwiches - Snack Pack - 12ct/12oz', 6.99, '($0.58/ounce)');
INSERT INTO ITEM VALUES('Organic Mini Sandwich Cheddar Cheese Crackers - 8oz/8ct - Good and Gather', 5.99, '($0.75/ounce)');
INSERT INTO ITEM VALUES('Ritz Bits Cheese Cracker Sandwiches - Snack Pack - 12ct/12oz', 6.99, '($0.58/ounce)');
INSERT INTO ITEM VALUES('Nature Valley Sweet N Salty Granola Bars - 18ct/1.49oz', 8.99, '($0.25/ounce)');
INSERT INTO ITEM VALUES('Nature Valley Sweet and Salty Dark Chocolate-Peanut and Almond Granola Bars - 7.4oz/6ct', 3.59, '($0.50/ounce)');
INSERT INTO ITEM VALUES("Nature Valley Crunchy Oats 'N Honey Granola Bars - 12ct", 3.59, '($0.40/ounce)');
INSERT INTO ITEM VALUES("Hershey's Milk Chocolate Candy Bar - 6ct", 5.49, '($0.59/ounce)');
INSERT INTO ITEM VALUES("Tony's Chocolate Sampler Pack Candy - 10.16oz/6ct", 9.99, '($0.98/ounce)');
INSERT INTO ITEM VALUES('Lindt Excellence Sea Salt Dark Chocolate Candy Bar - 3.5 oz.', 3.39, '($0.97/ounce)');
INSERT INTO ITEM VALUES('Milk Chocolate Bar Multipack Candy - 9.1oz/6ct - Favorite Day', 3.49, '($0.38/ounce)');
INSERT INTO ITEM VALUES('InnovAsian Frozen Sticky White Rice - 18oz', 4.29, '($0.24/ounce)');
INSERT INTO ITEM VALUES('Jasmine Rice - 2lbs - Good and Gather', 3.49, '($0.11/ounce)');
INSERT INTO ITEM VALUES('Rana 5 Cheese Tortellini - 20oz', 7.99, '($0.40/ounce)');
INSERT INTO ITEM VALUES('Goodles Dry Pasta Loopdy-Loos - 8 oz', 3.59, '($0.45/ounce)');
INSERT INTO ITEM VALUES('Rotini - 16oz - Good and Gather', 1.29, '($0.08/ounce)');
INSERT INTO ITEM VALUES('Rigatoni - 16oz - Good and Gather', 1.29, '($0.08/ounce)');
INSERT INTO ITEM VALUES('Old El Paso Traditional Refried Beans - 16oz', 1.99, '($0.12/ounce)');
INSERT INTO ITEM VALUES('Somos Mexican Black Beans Ready to Eat - 10oz', 3.79, '($0.38/ounce)');
INSERT INTO ITEM VALUES('Black Beans - 15.5oz - Good and Gather', 0.95, '($0.06/ounce)');
INSERT INTO ITEM VALUES('Low Sodium Black Beans - 15.5oz - Good and Gather', 0.95, '($0.06/ounce)');
INSERT INTO ITEM VALUES('Muir Glen Organic Diced Tomatoes No Salt Added - 14.5oz', 2.69, '($0.19/ounce)');
INSERT INTO ITEM VALUES('Muir Glen Fire Roasted Diced Tomatoes - 14oz', 2.69, '($0.19/ounce)');
INSERT INTO ITEM VALUES('Petite Diced Tomatoes 14.5oz - Good and Gather', 1.19, '($0.08/ounce)');
INSERT INTO ITEM VALUES('Crushed Tomatoes 28oz - Good and Gather', 2.19, '($0.08/ounce)');
INSERT INTO ITEM VALUES('Progresso Rich and Hearty Savory Beef Barley Vegetable Soup - 18.6oz', 2.39, '($0.13/ounce)');
INSERT INTO ITEM VALUES('Progresso Gluten Free Rich and Hearty Beef Pot Roast with Country Vegetables Soup - 18.5oz', 2.39, '($0.13/ounce)');
INSERT INTO ITEM VALUES('Progresso Rich and Hearty Chicken and Homestyle Noodle Soup - 19oz', 2.39, '($0.13/ounce)');
INSERT INTO ITEM VALUES("Campbell's Chunky Classic Chicken Noodle Soup - 18.6oz", 2.49, '($0.13/ounce)');
INSERT INTO ITEM VALUES('Swanson Natural Goodness Gluten Free 33% Less Sodium Chicken Broth - 32oz', 2.69, '($0.08/ounce)');
INSERT INTO ITEM VALUES('Kettle and Fire Organic Gluten Free Chicken Bone Broth - 16.9oz', 7.39, '($0.44/ounce)');
INSERT INTO ITEM VALUES('Chicken Broth - 32oz - Good and Gather', 1.59, '($0.05/ounce)');
INSERT INTO ITEM VALUES('Vegetable Broth - 32oz - Good and Gather', 1.59, '($0.05/ounce)');
INSERT INTO ITEM VALUES('Old El Paso Vegetarian Refried Beans - 16oz', 1.99, '($0.12/ounce)');
INSERT INTO ITEM VALUES('Cut Green Beans 14.5oz - Good and Gather', 0.75, '($0.05/ounce)');
INSERT INTO ITEM VALUES('Golden Sweet Whole Kernel Corn - 15.25oz - Good and Gather', 0.75, '($0.05/ounce)');
INSERT INTO ITEM VALUES('Sliced Carrots 14.5oz - Good and Gather', 1.19, '($0.08/ounce)');
INSERT INTO ITEM VALUES('Old El Paso Traditional Refried Beans - 16oz', 1.99, '($0.12/ounce)');
INSERT INTO ITEM VALUES('Old El Paso Refried Black Beans - 16oz', 1.99, '($0.12/ounce)');
INSERT INTO ITEM VALUES('Black Beans - 15.5oz - Good and Gather', 0.95, '($0.06/ounce)');
INSERT INTO ITEM VALUES('Organic Low Sodium 3 Bean Blend - 15oz - Good and Gather', 1.29, '($0.09/ounce)');
INSERT INTO ITEM VALUES('OLIPOP Cherry Cola Prebiotic Soda - 4ct/12 fl oz', 9.49, '($0.20/fluid ounce)');
INSERT INTO ITEM VALUES('OLIPOP Strawberry Vanilla Prebiotic Soda - 4ct/12 fl oz', 9.49, '($0.20/fluid ounce)');
INSERT INTO ITEM VALUES('Sliced Peaches in 100% Juice 14.5oz - Market Pantry', 1.49, '($0.10/ounce)');
INSERT INTO ITEM VALUES('Del Monte Pineapple Chunks in 100% Juice 20oz', 1.79, '($0.09/ounce)');
INSERT INTO ITEM VALUES('Jif To Go Creamy Peanut Butter - 12oz/8pk', 3.19, '($0.27/ounce)');
INSERT INTO ITEM VALUES('Jif No Added Sugar* Peanut Butter - 15.5oz', 3.39, '($0.22/ounce)');
INSERT INTO ITEM VALUES('Creamy Peanut Butter - 16oz - Good and Gather', 1.69, '($0.11/ounce)');
INSERT INTO ITEM VALUES('Jif Creamy Peanut Butter - 16oz', 3.19, '($0.20/ounce)');
INSERT INTO ITEM VALUES("Smucker's Squeeze Grape Jelly - 20oz", 3.19, '($0.16/ounce)');
INSERT INTO ITEM VALUES("Smucker's Squeeze Strawberry Fruit Spread - 20oz", 3.19, '($0.16/ounce)');
INSERT INTO ITEM VALUES("Smucker's Squeeze Strawberry Fruit Spread - 20oz", 3.19, '($0.16/ounce)');
INSERT INTO ITEM VALUES("Smucker's Squeeze Grape Jelly - 20oz", 3.19, '($0.16/ounce)');
INSERT INTO ITEM VALUES('Pearl Milling Company Original Syrup - 24 fl oz.', 3.69, '($0.15/fluid ounce)');
INSERT INTO ITEM VALUES('Pearl Milling Company Butter Rich Syrup - 24 fl oz.', 3.69, '($0.15/fluid ounce)');
INSERT INTO ITEM VALUES('Original Syrup Sugar Free - 24oz - Favorite Day', 2.29, '($0.10/ounce)');
INSERT INTO ITEM VALUES('Pearl Milling Company Original Syrup - 24 fl oz.', 3.69, '($0.15/fluid ounce)');
INSERT INTO ITEM VALUES("Nature Nate's 100% Pure Raw Unfiltered Organic Honey – 16oz", 9.99, '($0.62/ounce)');
INSERT INTO ITEM VALUES('Local Hive Colorado Raw and Unfiltered Honey -12oz', 6.49, '($0.54/ounce)');
INSERT INTO ITEM VALUES('Pure Clover Honey - 12oz - Good and Gather', 4.19, '($0.35/ounce)');
INSERT INTO ITEM VALUES('Organic Raw Unfiltered Pure Honey - 12oz - Good and Gather', 4.99, '($0.42/ounce)');
INSERT INTO ITEM VALUES("Bob's Red Mill Gluten Free 1-to-1 Baking Flour - 44oz", 9.79, '($0.22/ounce)');
INSERT INTO ITEM VALUES("Bob's Red Mill Gluten Free Super Fine Almond Flour - 16oz", 9.49, '($0.59/ounce)');
INSERT INTO ITEM VALUES('Unbleached All Purpose Flour - 5lbs - Good and Gather', 2.89, '($0.04/ounce)');
INSERT INTO ITEM VALUES('All Purpose Flour - 5lbs - Market Pantry', 2.89, '($0.04/ounce)');
INSERT INTO ITEM VALUES('Truvia Original Calorie-Free Sweetener from the Stevia Leaf - 40 packets/2.82oz', 3.79, '($1.34/ounce)');
INSERT INTO ITEM VALUES('Truvia Sweet Complete Calorie-Free Sweetener from the Stevia Leaf - 16oz', 7.29, '($0.46/ounce)');
INSERT INTO ITEM VALUES('Granulated Sugar - 4lbs - Good and Gather', 3.39, '($0.05/ounce)');
INSERT INTO ITEM VALUES('Domino Premium Pure Cane Granulated Sugar 4 lb', 3.49, '($0.05/ounce)');
INSERT INTO ITEM VALUES('McCormick Sea Salt Grinder - 2.12oz', 2.39, '($1.13/ounce)');
INSERT INTO ITEM VALUES('Iodized Salt - 26oz - Good and Gather', 0.69, '($0.03/ounce)');
INSERT INTO ITEM VALUES('Morton Iodized Salt - 26oz', 1.59, '($0.06/ounce)');
INSERT INTO ITEM VALUES('McCormick Pure Ground Black Pepper - 3oz', 3.79, '($1.26/ounce)');
INSERT INTO ITEM VALUES('McCormick Black Peppercorn Grinder - 1oz', 2.59, '($2.59/ounce)');
INSERT INTO ITEM VALUES('Ground Black Pepper - 3oz - Good and Gather', 2.89, '($0.96/ounce)');
INSERT INTO ITEM VALUES('Tri-Colored Bell Peppers - 16oz/3ct - Good and Gather (Packaging May Vary)', 2.99, '($0.19/ounce)');
INSERT INTO ITEM VALUES("Lawry's Seasoned Salt - 8oz", 3.19, '($0.40/ounce)');
INSERT INTO ITEM VALUES('McCormick Pure Ground Black Pepper - 3oz', 3.79, '($1.26/ounce)');
INSERT INTO ITEM VALUES('Onion Powder - 2.62oz - Good and Gather', 1.19, '($0.45/ounce)');
INSERT INTO ITEM VALUES('Ground Italian Seasoning - 0.75oz - Good and Gather', 1.19, '($1.59/ounce)');
INSERT INTO ITEM VALUES('Organic Extra Virgin Olive Oil - 16.9 fl oz - Good and Gather', 6.39, '($0.38/fluid ounce)');
INSERT INTO ITEM VALUES('Country Crock Original Vegetable Oil Spread Tub - 15oz', 3.69, '($0.25/ounce)');
INSERT INTO ITEM VALUES("I Can't Believe It's Not Butter! Original Vegetable Oil Spray - 8oz", 4.29, '($0.54/ounce)');
INSERT INTO ITEM VALUES('White Distilled Vinegar - 16 fl oz - Good and Gather', 0.85, '($0.05/fluid ounce)');
INSERT INTO ITEM VALUES('Multipurpose Vinegar - 128 fl oz - Smartly', 4.99, '($0.04/fluid ounce)');
INSERT INTO ITEM VALUES('White Distilled Vinegar - 64oz - Good and Gather', 2.99, '($0.05/fluid ounce)');
INSERT INTO ITEM VALUES('Kikkoman Soy Sauce 15oz', 3.79, '($0.25/fluid ounce)');
INSERT INTO ITEM VALUES('Kikkoman Less Sodium Soy Sauce 10 fl oz', 3.69, '($0.37/fluid ounce)');
INSERT INTO ITEM VALUES('Kikkoman Less Sodium Soy Sauce 10 fl oz', 3.69, '($0.37/fluid ounce)');
INSERT INTO ITEM VALUES('Soy Sauce Less Sodium - 15oz - Market Pantry', 1.69, '($0.11/fluid ounce)');
INSERT INTO ITEM VALUES('Kikkoman Teriyaki Marinade and Sauce 10oz', 3.29, '($0.33/fluid ounce)');
INSERT INTO ITEM VALUES("Lawry's Teriyaki Marinade - 12oz", 3.19, '($0.27/fluid ounce)');
INSERT INTO ITEM VALUES('Sesame Teriyaki Sauce - 12oz - Good and Gather', 3.29, '($0.27/fluid ounce)');
INSERT INTO ITEM VALUES('Soy Vay Marinade and Sauce Veri Veri Teriyaki 21oz', 3.99, '($0.19/ounce)');
INSERT INTO ITEM VALUES('TABASCO Chipotle Pepper Sauce - 5oz', 3.79, '($0.76/fluid ounce)');
INSERT INTO ITEM VALUES('TABASCO Green Pepper Jalapeno Sauce - 5oz', 3.79, '($0.76/fluid ounce)');
INSERT INTO ITEM VALUES("Frank's RedHot Original Red Hot Sauce 12oz", 3.99, '($0.33/fluid ounce)');
INSERT INTO ITEM VALUES('Cholula Hot Sauce - 5oz', 4.29, '($0.86/fluid ounce)');
INSERT INTO ITEM VALUES('Kraft Sweet Honey BBQ Sauce - 18oz', 2.39, '($0.13/ounce)');
INSERT INTO ITEM VALUES('Kraft Original BBQ Sauce - 18oz', 2.39, '($0.13/ounce)');
INSERT INTO ITEM VALUES("Sweet Baby Ray's Barbecue Sauce - 18oz", 2.69, '($0.15/ounce)');
INSERT INTO ITEM VALUES("Sweet Baby Ray's No Sugar Added Original BBQ Sauce - 18.5oz", 3.79, '($0.20/ounce)');
INSERT INTO ITEM VALUES('Heinz Tomato Ketchup 32oz', 4.99, '($0.16/ounce)');
INSERT INTO ITEM VALUES('Heinz Tomato Ketchup - 38oz', 4.79, '($0.13/ounce)');
INSERT INTO ITEM VALUES('Heinz Tomato Ketchup 32oz', 4.99, '($0.16/ounce)');
INSERT INTO ITEM VALUES('Ketchup 20oz - Market Pantry', 1.19, '($0.06/ounce)');
INSERT INTO ITEM VALUES("French's Yellow Mustard Classic - 20oz", 2.99, '($0.15/ounce)');
INSERT INTO ITEM VALUES("French's Classic Yellow Mustard 14oz", 2.29, '($0.16/ounce)');
INSERT INTO ITEM VALUES('Yellow Mustard - 14oz - Market Pantry', 0.85, '($0.06/ounce)');
INSERT INTO ITEM VALUES("French's Yellow Mustard Classic - 20oz", 2.99, '($0.15/ounce)');
INSERT INTO ITEM VALUES('Kraft Reduced Fat Mayonnaise with Olive Oil - 30 fl oz', 5.29, '($0.18/fluid ounce)');
INSERT INTO ITEM VALUES('Kraft Real Mayonnaise 30 fl oz', 5.29, '($0.18/fluid ounce)');
INSERT INTO ITEM VALUES('Mayonnaise - 30oz - Market Pantry', 3.39, '($0.11/fluid ounce)');
INSERT INTO ITEM VALUES('Kraft Classic Catalina Salad Dressing 16fl oz', 3.19, '($0.20/fluid ounce)');
INSERT INTO ITEM VALUES('Hidden Valley Original Ranch Salad Dressing and Topping - Gluten Free - 8 fl oz', 2.89, '($0.36/fluid ounce)');
INSERT INTO ITEM VALUES('Olive Garden Signature Italian Salad Dressing - 16fl oz', 4.49, '($0.28/fluid ounce)');
INSERT INTO ITEM VALUES('Ranch Dressing 16fl oz - Market Pantry', 2.29, '($0.14/fluid ounce)');
INSERT INTO ITEM VALUES('Quaker Lower Sugar Variety Pack Oatmeal - 9.3oz', 3.69, '($0.40/ounce)');
INSERT INTO ITEM VALUES('Quaker Oats Old Fashioned Oats - 42oz', 4.99, '($0.12/ounce)');
INSERT INTO ITEM VALUES('Quaker Instant Oatmeal Maple Brown Sugar 8ct', 3.69, '($0.30/ounce)');
INSERT INTO ITEM VALUES('Quaker Fruit and Cream Instant Oatmeal Variety - 8ct/9.8oz', 3.69, '($0.44/ounce)');
INSERT INTO ITEM VALUES('Pearl Milling Company Buttermilk Complete Pancake and Waffle Mix - 2lb', 3.49, '($0.11/ounce)');
INSERT INTO ITEM VALUES('Pearl Milling Company Original Pancake and Waffle Mix - 2lb', 3.49, '($0.11/ounce)');
INSERT INTO ITEM VALUES('Pearl Milling Company Buttermilk Complete Pancake and Waffle Mix - 2lb', 3.49, '($0.11/ounce)');
INSERT INTO ITEM VALUES('Krusteaz Buttermilk Pancake Mix - 2lb', 3.19, '($0.10/ounce)');
INSERT INTO ITEM VALUES('GoNanas Chocolate Chip Banana Bread Mix - 12.3oz', 7.99, '($0.65/ounce)');
INSERT INTO ITEM VALUES('Kodiak Protein-Packed Muffin Mix Blueberry Lemon - 14oz', 7.29, '($0.52/ounce)');
INSERT INTO ITEM VALUES('Pillsbury Funfetti Premium Cake and Cupcake Mix - 15.25oz', 1.99, '($0.13/ounce)');
INSERT INTO ITEM VALUES('Red Lobster Cheddar Bay Biscuit Mix - 11.36oz', 2.99, '($0.26/ounce)');
INSERT INTO ITEM VALUES('Italian Seasoned Bread Crumbs 15oz - Market Pantry', 1.49, '($0.10/ounce)');
INSERT INTO ITEM VALUES('Plain Bread Crumbs 15oz - Market Pantry', 1.49, '($0.10/ounce)');
INSERT INTO ITEM VALUES('Plain Panko Bread Crumbs 8oz - Market Pantry', 2.29, '($0.29/ounce)');
INSERT INTO ITEM VALUES('Progresso Italian Style Bread Crumbs 15oz', 2.59, '($0.17/ounce)');
INSERT INTO ITEM VALUES('Betty Crocker Vanilla Super Moist Cake Mix - 13.25oz', 1.79, '($0.14/ounce)');
INSERT INTO ITEM VALUES('Betty Crocker Delights Rainbow Chip Super Moist Cake Mix - 13.25oz', 1.99, '($0.15/ounce)');
INSERT INTO ITEM VALUES('Betty Crocker Vanilla Super Moist Cake Mix - 13.25oz', 1.79, '($0.14/ounce)');
INSERT INTO ITEM VALUES('Betty Crocker Delights Rainbow Chip Super Moist Cake Mix - 13.25oz', 1.99, '($0.15/ounce)');
INSERT INTO ITEM VALUES('Betty Crocker Fudge Brownie Mix - 16.3oz', 2.29, '($0.14/ounce)');
INSERT INTO ITEM VALUES('Betty Crocker Supreme Chocolate Chunk Brownie Mix - 18oz', 2.89, '($0.16/ounce)');
INSERT INTO ITEM VALUES('Duncan Hines Chewy Fudge Brownie Mix - 18.3oz', 1.79, '($0.10/ounce)');
INSERT INTO ITEM VALUES('Betty Crocker Fudge Brownie Mix - 16.3oz', 2.29, '($0.14/ounce)');
INSERT INTO ITEM VALUES("Tate's Bake Shop Chocolate Chip Cookies - 7oz", 6.39, '($0.91/ounce)');
INSERT INTO ITEM VALUES('Keebler Vienna Fingers Cookies Original - 12oz', 3.79, '($0.32/ounce)');